### ISSUE TITLE
[Bug report] How we support Use statement

### ISSUE THREAD

**Issue by huangxiaopingRD** [datastrato/gravitino#1172]
### Describe what's wrong

Unable to execute `use` SQL.

Many engines only support the form of `catalog.schema.table`, but we have introduced the concept of `metalake` (`metalake.catalog.schema.table`), which causes some engines to be unable to correctly parse `"metalake.catalog"`, such as the trino engine.

### Error message and/or stacktrace

```
Execution of 'expected' query failed: use "test.memory".db_01
java.lang.AssertionError: Execution of 'expected' query failed: use "test.memory".db_01
	at org.testng.Assert.fail(Assert.java:83)
	at io.trino.testing.QueryAssertions.assertDistributedQuery(QueryAssertions.java:309)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:184)
	at io.trino.testing.QueryAssertions.assertQuery(QueryAssertions.java:157)
	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:334)
	at io.trino.testing.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:329)
	at com.datastrato.gravitino.trino.connector.TestGravitinoConnector.testUse(TestGravitinoConnector.java:152)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:145)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:92)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy2.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: org.jdbi.v3.core.statement.UnableToCreateStatementException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "use ""test.memory""[*].db_01"; SQL statement:
use "test.memory".db_01 [42000-220] [statement:"use "test.memory".db_01", arguments:{positional:{}, named:{}, finder:[]}]
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1789)
	at org.jdbi.v3.core.result.ResultProducers.lambda$createResultBearing$3(ResultProducers.java:94)
	at org.jdbi.v3.core.result.internal.ResultSetResultIterable.iterator(ResultSetResultIterable.java:51)
	at org.jdbi.v3.core.result.ResultIterable.stream(ResultIterable.java:266)
	at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:340)
	at org.jdbi.v3.core.result.ResultIterable.list(ResultIterable.java:315)
	at io.trino.testing.H2QueryRunner.execute(H2QueryRunner.java:197)
	at io.trino.testing.QueryAssertions.assertDistributedQuery(QueryAssertions.java:306)
	... 48 more
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "use ""test.memory""[*].db_01"; SQL statement:
use "test.memory".db_01 [42000-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.getSyntaxError(DbException.java:247)
	at org.h2.command.Parser.getSyntaxError(Parser.java:908)
	at org.h2.command.Parser.prepareCommand(Parser.java:580)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:634)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:557)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:639)
	at org.jdbi.v3.core.statement.DefaultStatementBuilder.create(DefaultStatementBuilder.java:57)
	at org.jdbi.v3.core.statement.SqlStatement.createStatement(SqlStatement.java:1812)
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1783)
	... 55 more

```

### How to reproduce

Add this UT to `TestGravitinoConnector`
```
  @Test
  public void testUse() throws Exception {
    String fullTableName = "\"test.memory\".db_01.tb_01";
    createTestTable(fullTableName);
    assertQuery("use \"test.memory\".db_01");
    // assertThat(computeActual("show tables").getOnlyColumnAsSet()).contains("tb_01");
    // cleanup
    dropTestTable(fullTableName);
  }
```

**Comment by yuqi1129** [comment]
@huangxiaopingRD 

It's not a bug actually, we have developed a Trino connector that makes Trino can query engines like `Hive`, `MySQL` through Gravitino and supports `metalake`. 

It's an occasional test error here for `TestGravitinoConnector` and I also met it in CI this afternoon and can't find what's the problem, maybe @diqiu50 we should work together to solve the test error.

**Comment by yuqi1129** [comment]
@huangxiaopingRD 
For information on Gravitino Trino connector, you can refer to https://datastrato.ai/docs/trino-connector/trino-connector

**Comment by huangxiaopingRD** [comment]
@yuqi1129 
I used the memory connector in the Gravitino Trino connector to test. There is such a usage scenario:
```
USE "metalake.catalog".dbname;
SHOW TABLES;
SELECT * from tabname
```
The following does indeed work normally：
```
SELECT * from "metalake.catalog".dbname.tabname
```

**Comment by diqiu50** [comment]
@huangxiaopingRD It works in the Trino CLI.  I will check later if there is a problem in TestGravitinoConnector or if it's not supported.

**Comment by diqiu50** [comment]
@huangxiaopingRD 
I have confirmed that the QueryRunner used in the test does not support session switching within the 'USE' statement.
```
  @Test
  public void testUse() throws Exception {
    String fullTableName = "\"test.memory\".db_01.tb_01";
    createTestTable(fullTableName);
    //assertQuery("use \"test.memory\".db_01");
    Session session = testSessionBuilder().setCatalog("\"test.memory\"").setSchema("db_01").build();
    assertThat(computeActual(session, "show tables").getOnlyColumnAsSet()).contains("tb_01");
    // cleanup
    dropTestTable(fullTableName);
  }
```
