### ISSUE TITLE
[Bug report] Tests freeze and fail to complete with Azul Zulu17 JDK

### ISSUE THREAD

**Issue by justinmclean** [datastrato/gravitino#1373]
### Describe what's wrong

The trino connector tests  freeze and fail to complete when building under Azul Zulu17 JDK.

### Error message and/or stacktrace

N/A

### How to reproduce

Run `./gradlew build` when use Java version:
```shell
java -version               
openjdk version "17.0.9" 2023-10-17 LTS
OpenJDK Runtime Environment Zulu17.46+19-CA (build 17.0.9+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.46+19-CA (build 17.0.9+8-LTS, mixed mode, sharing)
```

**Comment by yuqi1129** [comment]
@justinmclean 
It's OK with me
<img width="1715" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/81bdc679-4510-47c5-a90a-c19bb726e268">

**Comment by yuqi1129** [comment]
So 
```
mac-docker-connector status ..................................... [stop]
OrbStack status ................................................. [yes]
```

Is `mac-docker-connector` is `running` and `OrbStack status` is `stop`?

**Comment by yuqi1129** [comment]
![image](https://github.com/datastrato/gravitino/assets/15794564/e652dcca-79af-412d-bc34-86db7412abd5)

**Comment by justinmclean** [comment]
I believe I tried it with Is mac-docker-connector status stop and OrbStack status is no. It is likely what a new user would do.

**Comment by yuqi1129** [comment]
Use OpenJDK17 can reproduce it. The test stuck in `TestGravitinoConnector`

Here is the stack 
```
"/127.0.0.1:40244 to /127.0.0.1:38815 workers" #16 prio=5 os_prio=0 cpu=8.77ms elapsed=680.00s tid=0x00007ffff9335080 nid=0x77e waiting on condition  [0x00007fffd16fb000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.9/Native Method)
	- parking to wait for  <0x00000000e1efd100> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.9/LockSupport.java:341)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@17.0.9/AbstractQueuedSynchronizer.java:506)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.9/ForkJoinPool.java:3465)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.9/ForkJoinPool.java:3436)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@17.0.9/AbstractQueuedSynchronizer.java:1623)
	at org.gradle.internal.remote.internal.hub.queue.EndPointQueue.take(EndPointQueue.java:49)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:403)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.9/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.9/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.9/Thread.java:840)

"/127.0.0.1:40244 to /127.0.0.1:38815 workers Thread 2" #17 prio=5 os_prio=0 cpu=1698.07ms elapsed=679.95s tid=0x00007ffff93552f0 nid=0x77f waiting on condition  [0x00007fffd15fb000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.9/Native Method)
	- parking to wait for  <0x00000000e1efd700> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.9/LockSupport.java:341)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@17.0.9/AbstractQueuedSynchronizer.java:506)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.9/ForkJoinPool.java:3465)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.9/ForkJoinPool.java:3436)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@17.0.9/AbstractQueuedSynchronizer.java:1623)
	at org.gradle.internal.remote.internal.hub.queue.EndPointQueue.take(EndPointQueue.java:49)
	at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:322)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.9/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.9/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.9/Thread.java:840)

"/127.0.0.1:40244 to /127.0.0.1:38815 workers Thread 3" #18 prio=5 os_prio=0 cpu=18.68ms elapsed=679.95s tid=0x00007ffff9341740 nid=0x780 runnable  [0x00007fffd14fb000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPoll.wait(java.base@17.0.9/Native Method)
	at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@17.0.9/EPollSelectorImpl.java:118)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@17.0.9/SelectorImpl.java:129)
	- locked <0x00000000e1efdb70> (a sun.nio.ch.Util$2)
	- locked <0x00000000e1efdb20> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@17.0.9/SelectorImpl.java:146)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketInputStream.read(SocketConnection.java:185)
	at com.esotericsoftware.kryo.io.Input.fill(Input.java:146)
	at com.esotericsoftware.kryo.io.Input.require(Input.java:178)
	at com.esotericsoftware.kryo.io.Input.readByte(Input.java:295)
	at org.gradle.internal.serialize.kryo.KryoBackedDecoder.readByte(KryoBackedDecoder.java:88)
	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:64)
	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:52)
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
	at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:270)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.9/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.9/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.9/Thread.java:840)
```

**Comment by yuqi1129** [comment]
Updating the Gradle version to `8.5` can't address this issue.  @diqiu50 Please also take a look, I wander why only this test is hanging here.

**Comment by yuqi1129** [comment]
![image](https://github.com/datastrato/gravitino/assets/15794564/32fb41c3-071b-4f0a-9888-db3a76104bc8)
MacOS:  Two processes are parent and child to each other, and the processes can't be killed.
