### ISSUE TITLE
[Bug report] TestHTTPClient may be crash when there is another process using 1080 port

### ISSUE THREAD

**Issue by coolderli** [datastrato/gravitino#1474]
### Describe what's wrong

1. The port 1080 may be used by another process, then the `com.datastrato.gravitino.client.TestHTTPClient` may be crashed.

### Error message and/or stacktrace

```
org.mockserver.httpclient.SocketConnectionException: Channel handler removed before valid response has been received
	at org.mockserver.httpclient.HttpClientConnectionErrorHandler.handlerRemoved(HttpClientConnectionErrorHandler.java:21)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:1122)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637)
	at io.netty.channel.DefaultChannelPipeline.destroyDown(DefaultChannelPipeline.java:876)
	at io.netty.channel.DefaultChannelPipeline.destroyUp(DefaultChannelPipeline.java:844)
	at io.netty.channel.DefaultChannelPipeline.destroy(DefaultChannelPipeline.java:836)
	at io.netty.channel.DefaultChannelPipeline.access$700(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1392)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:215)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:195)
	at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:821)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:821)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
```

### How to reproduce

Start another process on port 1080, then these unit tests will fail.

**Comment by coolderli** [comment]
Just like on my computer, this port is occupied by V2array, and then this test crashes.
![image](https://github.com/datastrato/gravitino/assets/38486782/6cb1f1af-2b3e-44d3-94ab-2b13b8d1ae50)
