### ISSUE TITLE
[Bug report] createTable HiveTable failed if comment is null

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#1544]
### Describe what's wrong

createTable HiveTable failed if comment is null

### Error message and/or stacktrace

```java
Caused by: java.lang.NullPointerException
	at org.apache.thrift.protocol.TBinaryProtocol.writeString(TBinaryProtocol.java:206)
	at org.apache.hadoop.hive.metastore.api.Table$TableStandardScheme.write(Table.java:1695)
	at org.apache.hadoop.hive.metastore.api.Table$TableStandardScheme.write(Table.java:1477)
	at org.apache.hadoop.hive.metastore.api.Table.write(Table.java:1325)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_args$create_table_with_environment_context_argsStandardScheme.write(ThriftHiveMetastore.java:41610)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_args$create_table_with_environment_context_argsStandardScheme.write(ThriftHiveMetastore.java:41565)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_args.write(ThriftHiveMetastore.java:41505)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:71)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.send_create_table_with_environment_context(ThriftHiveMetastore.java:1197)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_table_with_environment_context(ThriftHiveMetastore.java:1188)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.create_table_with_environment_context(HiveMetaStoreClient.java:2396)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:750)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:738)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:169)
	at com.sun.proxy.$Proxy107.createTable(Unknown Source)
	at com.datastrato.gravitino.catalog.hive.HiveCatalogOperations.lambda$createTable$20(HiveCatalogOperations.java:596)
	at com.datastrato.gravitino.utils.ClientPoolImpl.run(ClientPoolImpl.java:59)
	at com.datastrato.gravitino.utils.ClientPoolImpl.run(ClientPoolImpl.java:52)
	at com.datastrato.gravitino.catalog.hive.HiveCatalogOperations.createTable(HiveCatalogOperations.java:594)
```

### How to reproduce

1. set TASBLE_COMMENT = null
2. run CatalogHiveIT#testCreateHiveTable

**Comment by FANNG1** [comment]
I prefer to add a default value to comment, is null, set to a empty string.
