### ISSUE TITLE
[Bug report] create Iceberg table failed if comment is null 

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#1546]
### Describe what's wrong

create Iceberg table failed if comment is null 

### Error message and/or stacktrace

```
java.lang.IllegalArgumentException: Failed to operate table(s) [iceberg_it_table_57dc4f9e] operation [CREATE] under schema [iceberg_it_schema_60a9a4a2], reason [IllegalArgumentException]
java.lang.IllegalArgumentException: Invalid value for properties [comment]: null
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
	at org.apache.iceberg.rest.requests.CreateTableRequest$Builder.setProperties(CreateTableRequest.java:154)
	at com.datastrato.gravitino.catalog.lakehouse.iceberg.IcebergTable.toCreateTableRequest(IcebergTable.java:57)
	at com.datastrato.gravitino.catalog.lakehouse.iceberg.IcebergCatalogOperations.createTable(IcebergCatalogOperations.java:526)
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.lambda$null$30(CatalogOperationDispatcher.java:432)
	at com.datastrato.gravitino.catalog.CatalogManager$CatalogWrapper.lambda$doWithTableOps$1(CatalogManager.java:97)
	at com.datastrato.gravitino.utils.IsolatedClassLoader.withClassLoader(IsolatedClassLoader.java:69)
	at com.datastrato.gravitino.catalog.CatalogManager$CatalogWrapper.doWithTableOps(CatalogManager.java:92)
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.lambda$createTable$31(CatalogOperationDispatcher.java:430)
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.doWithCatalog(CatalogOperationDispatcher.java:696)
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.createTable(CatalogOperationDispatcher.java:427)
	at com.datastrato.gravitino.server.web.rest.TableOperations.lambda$createTable$1(TableOperations.java:96)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at com.datastrato.gravitino.utils.PrincipalUtils.doAs(PrincipalUtils.java:25)
	at com.datastrato.gravitino.server.web.Utils.doAs(Utils.java:110)
	at com.datastrato.gravitino.server.web.rest.TableOperations.createTable(TableOperations.java:88)

```

### How to reproduce

1. set table_comment = null
2. run CatalogIcebergIT#testCreateAndLoadIcebergTable

**Comment by FANNG1** [comment]
please check JDBC table too, @Clearvive
