### ISSUE TITLE
[Bug report] couldn't get schema comment from mysql catalog

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#1717]
### Version

main branch

### Describe what's wrong

couldn't get schema comment from mysql catalog

### Error message and/or stacktrace

```
org.opentest4j.AssertionFailedError: expected: <comment> but was: <null>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
	at com.datastrato.gravitino.integration.test.catalog.jdbc.mysql.CatalogMysqlIT.testCreateAndLoadSchema(CatalogMysqlIT.java:579)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
```

### How to reproduce

```java
  @Test
  void testCreateAndLoadSchema() {
    String testSchemaName = "test";
    NameIdentifier ident = NameIdentifier.of(metalakeName, catalogName, testSchemaName);

    Schema schema = catalog.asSchemas().createSchema(ident, "comment", null);
    Assertions.assertEquals("anonymous", schema.auditInfo().creator());
    Assertions.assertEquals("comment", schema.comment());
    schema = catalog.asSchemas().loadSchema(ident);
    Assertions.assertEquals("anonymous", schema.auditInfo().creator());
    Assertions.assertEquals("comment", schema.comment());
}
```

**Comment by FANNG1** [comment]
Mysql doesn't support set comment on databases, cc @jerryshao @Clearvive .
