### ISSUE TITLE
[Bug report] java.lang.NullPointerException at com.datastrato.gravitino.integration.test.container.ContainerSuite.createDockerNetwork(ContainerSuite.java:163)

### ISSUE THREAD

**Issue by puchengy** [datastrato/gravitino#1779]
### Version

main branch

### Describe what's wrong

Failed to run integration tests.

### Error message and/or stacktrace

7 tests failed because of same error.
```
TrinoConnectorIT > initializationError FAILED
    java.lang.ExceptionInInitializerError
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeAllMethod(TimeoutExtension.java:68)
        at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllMethods$11(ClassBasedTestDescriptor.java:397)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllMethods(ClassBasedTestDescriptor.java:395)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:209)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:80)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
        at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:110)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:90)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:85)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

        Caused by:
        java.lang.RuntimeException: Failed to initialize ContainerSuite
            at com.datastrato.gravitino.integration.test.container.ContainerSuite.<init>(ContainerSuite.java:53)
            at com.datastrato.gravitino.integration.test.container.ContainerSuite.getInstance(ContainerSuite.java:61)
            at com.datastrato.gravitino.integration.test.trino.TrinoConnectorIT.<clinit>(TrinoConnectorIT.java:64)

            Caused by:
            java.lang.NullPointerException
                at com.datastrato.gravitino.integration.test.container.ContainerSuite.createDockerNetwork(ContainerSuite.java:163)
                at com.datastrato.gravitino.integration.test.container.ContainerSuite.<init>(ContainerSuite.java:50)
                ... 2 more
```

### How to reproduce

```
------------------------------------------------------------
Gradle 8.2
------------------------------------------------------------

Build time:   2023-06-30 18:02:30 UTC
Revision:     5f4a070a62a31a17438ac998c2b849f4f6892877

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          1.8.0_362 (Amazon.com Inc. 25.362-b08)
OS:           Mac OS X 14.2.1 aarch64
```

Docker software version: Docker Desktop 4.27.0 (135262)

**Comment by jerryshao** [comment]
Thanks @puchengy for your reporting issue. @xunliu @diqiu50 can you please help to look at this issue?

**Comment by xunliu** [comment]
hi @puchengy Thank you for your report on this bug.

I created a branch `issue-1779` in my repo to try to fix this problem, Please execute the next command and help me run it in your local environment if you have time, Thanks.
```
branch_name=issue-1779 && git fetch git@github.com:xunliu/gravitino.git ${branch_name}:${branch_name} && git checkout ${branch_name}
```

**Comment by zivali** [comment]
Hi, I encountered similar issue after I updated my Docker Desktop this week. The following is my environment.
```
------------------------------------------------------------
Gradle 8.2
------------------------------------------------------------

Build time:   2023-06-30 18:02:30 UTC
Revision:     5f4a070a62a31a17438ac998c2b849f4f6892877

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          1.8.0_352 (Azul Systems, Inc. 25.352-b08)
OS:           Mac OS X 14.2.1 aarch64
Docker Desktop 4.27.2 (137060)

```

Example build error:
```
java.lang.ExceptionInInitializerError
...
Suppressed: java.lang.NoClassDefFoundError: Could not initialize class com.datastrato.gravitino.integration.test.trino.TrinoConnectorIT
Caused by: java.lang.RuntimeException: Failed to initialize ContainerSuite
	at com.datastrato.gravitino.integration.test.container.ContainerSuite.<init>(ContainerSuite.java:53)
	at com.datastrato.gravitino.integration.test.container.ContainerSuite.getInstance(ContainerSuite.java:61)
	at com.datastrato.gravitino.integration.test.trino.TrinoConnectorIT.<clinit>(TrinoConnectorIT.java:67)
	... 74 more
Caused by: java.lang.NullPointerException
	at com.datastrato.gravitino.integration.test.container.ContainerSuite.createDockerNetwork(ContainerSuite.java:163)
	at com.datastrato.gravitino.integration.test.container.ContainerSuite.<init>(ContainerSuite.java:50)
	... 76 more
```

Running the above command provided by @xunliu, the output becomes:
It seems like we may need to modify the docker network in order to make the build works? 🤔
```
java.lang.ExceptionInInitializerError
...
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class com.datastrato.gravitino.integration.test.trino.TrinoConnectorIT
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
		at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptAfterAllMethod(TimeoutExtension.java:116)
		at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllMethods$13(ClassBasedTestDescriptor.java:425)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllMethods$14(ClassBasedTestDescriptor.java:423)
		at java.util.ArrayList.forEach(ArrayList.java:1259)
		at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeAfterAllMethods(ClassBasedTestDescriptor.java:423)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:225)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:80)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:161)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:161)
		... 48 more
Caused by: java.lang.RuntimeException: Failed to initialize ContainerSuite
	at com.datastrato.gravitino.integration.test.container.ContainerSuite.<init>(ContainerSuite.java:53)
	at com.datastrato.gravitino.integration.test.container.ContainerSuite.getInstance(ContainerSuite.java:61)
	at com.datastrato.gravitino.integration.test.trino.TrinoConnectorIT.<clinit>(TrinoConnectorIT.java:64)
	... 74 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: The Docker of the network 8e823275-be52-4287-9d0e-42c68a71c259 subnet 10.20.30.0/28 conflicts with the `gravitino-ci-network` 10.20.30.0/28
	at com.datastrato.gravitino.integration.test.container.ContainerSuite.createDockerNetwork(ContainerSuite.java:185)
	at com.datastrato.gravitino.integration.test.container.ContainerSuite.<init>(ContainerSuite.java:50)
	... 76 more
Caused by: java.lang.RuntimeException: The Docker of the network 8e823275-be52-4287-9d0e-42c68a71c259 subnet 10.20.30.0/28 conflicts with the `gravitino-ci-network` 10.20.30.0/28
	at com.datastrato.gravitino.integration.test.container.ContainerSuite.createDockerNetwork(ContainerSuite.java:180)
	... 77 more

**Comment by xunliu** [comment]
hi @zivali thank you report this problem.
I think your problem is docker network conflicts
Please execute command `docker network inspect 8e823275-be52-4287-9d0e-42c68a71c259` or `docker network inspect 8e823275` and attach result in the a new comment.

**Comment by zivali** [comment]
Hi @xunliu Thank you! Following is the output:
```
➤ docker network inspect 8e823275-be52-4287-9d0e-42c68a71c259
[
    {
        "Name": "8e823275-be52-4287-9d0e-42c68a71c259",
        "Id": "e74bf6d9826ba469386a1d0cc5fa3c293857d8391a8282f6bf2f05aff6480ea4",
        "Created": "2024-03-06T15:10:17.283847587Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.20.30.0/28",
                    "IPRange": "10.20.30.14/28",
                    "Gateway": "10.20.30.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},
        "Labels": {
            "org.testcontainers": "true",
            "org.testcontainers.lang": "java",
            "org.testcontainers.sessionId": "c11b0880-ead0-4e84-9b96-064cd6fbad59",
            "org.testcontainers.version": "1.19.0"
        }
    }
]

**Comment by diqiu50** [comment]
@xunliu  I remember you fix the problem before.
The `SUBNET` is conflict with  `IPRANGE`,  `IPRANGE` should be "10.20.30.0/28" too.
```
  public static final String CONTAINER_NETWORK_SUBNET = "10.20.30.0/28";
  private static final String CONTAINER_NETWORK_GATEWAY = "10.20.30.1";
  private static final String CONTAINER_NETWORK_IPRANGE = "10.20.30.14/28";
```

**Comment by xunliu** [comment]
> Hi @xunliu Thank you! Following is the output:
> 
> ```
> ➤ docker network inspect 8e823275-be52-4287-9d0e-42c68a71c259
> [
>     {
>         "Name": "8e823275-be52-4287-9d0e-42c68a71c259",
>         "Id": "e74bf6d9826ba469386a1d0cc5fa3c293857d8391a8282f6bf2f05aff6480ea4",
>         "Created": "2024-03-06T15:10:17.283847587Z",
>         "Scope": "local",
>         "Driver": "bridge",
>         "EnableIPv6": false,
>         "IPAM": {
>             "Driver": "default",
>             "Options": null,
>             "Config": [
>                 {
>                     "Subnet": "10.20.30.0/28",
>                     "IPRange": "10.20.30.14/28",
>                     "Gateway": "10.20.30.1"
>                 }
>             ]
>         },
>         "Internal": false,
>         "Attachable": false,
>         "Ingress": false,
>         "ConfigFrom": {
>             "Network": ""
>         },
>         "ConfigOnly": false,
>         "Containers": {},
>         "Options": {},
>         "Labels": {
>             "org.testcontainers": "true",
>             "org.testcontainers.lang": "java",
>             "org.testcontainers.sessionId": "c11b0880-ead0-4e84-9b96-064cd6fbad59",
>             "org.testcontainers.version": "1.19.0"
>         }
>     }
> ]
> ```

hi @zivali you can execute `docker network rm 8e823275-be52-4287-9d0e-42c68a71c259` to remove this duplicate network. and re-execute Gravitino IT test.

**Comment by zivali** [comment]
After removing the network and pulling from main branch, I am able to successfully run tests again now. Thank you for all your supports! :)
