### ISSUE TITLE
[Improvement]  too many trino container failed log

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#2050]
### What would you like to be improved?

https://github.com/datastrato/gravitino/actions/runs/7773865534/job/21198055421?pr=2046  trino container test is supporsed to be finished,  now is running WebTEST but still print many error messages.

```
2024-02-04 12:21:14 INFO  ChromeWebDriverProvider:146 - Remove temp directory: /home/runner/work/gravitino/gravitino/integration-test/build/chrome-1707049271104
2024-02-04 12:21:14 INFO  ChromeWebDriverProvider:81 - Download the chromeDriver to /home/runner/work/gravitino/gravitino/integration-test/build/chrome successfully.
2024-02-04 12:21:14 INFO  PrintingContainerLog:29 - TrinoContainer | 2024-02-04T12:21:14.931Z   INFO    gravitino-connector-schedule-0  stdout  2024-02-04 12:21:14 ERROR CatalogConnectorManager:115 - Load Metalake trinoit_metalake_c96014a5 failed.
2024-02-04 12:21:14 INFO  PrintingContainerLog:29 - TrinoContainer | com.datastrato.gravitino.exceptions.RESTException: Error occurred while processing GET request
2024-02-04 12:21:14 INFO  PrintingContainerLog:29 - TrinoContainer |    at com.datastrato.gravitino.client.HTTPClient.execute(HTTPClient.java:377) ~[gravitino-client-java-runtime-0.4.0-SNAPSHOT.jar:?]
2024-02-04 12:21:14 INFO  PrintingContainerLog:29 - TrinoContainer |    at com.datastrato.gravitino.client.HTTPClient.execute(HTTPClient.java:272) ~[gravitino-client-java-runtime-0.4.0-SNAPSHOT.jar:?]
2024-02-04 12:21:14 INFO  PrintingContainerLog:29 - TrinoContainer |    at com.datastrato.gravitino.client.HTTPClient.get(HTTPClient.java:417) ~[gravitino-client-java-runtime-0.4.0-SNAPSHOT.jar:?]
2024-02-04 12:21:14 INFO  PrintingContainerLog:29 - TrinoContainer |    at com.datastrato.gravitino.client.RESTClient.get(RESTClient.java:165) ~[gravitino-client-java-runtime-0.4.0-SNAPSHOT.jar:?]
2024-02-04 12:21:14 INFO  PrintingContainerLog:29 - TrinoContainer |    at com.datastrato.gravitino.client.GravitinoClient.loadMetalake(GravitinoClient.java:95) ~[gravitino-client-java-runtime-0.4.0-SNAPSHOT.jar:?]
2024-02-04 12:21:14 INFO  PrintingContainerLog:29 - TrinoContainer |    at com.datastrato.gravitino.trino.connector.catalog.CatalogConnectorManager.loadMetalake(CatalogConnectorManager.java:110) ~[gravitino-trino-connector-0.4.0-SNAPSHOT.jar:?]
```

**Comment by yuqi1129** [comment]
It cannot be reproduced in the latest main branch

**Comment by diqiu50** [comment]
After splitting the integration tests, this issue should no longer exist.
A better solution would be to shut down the Trino container after use.
