### ISSUE TITLE
[Bug report] `TrinoQueryIT` failed

### ISSUE THREAD

**Issue by mchades** [datastrato/gravitino#2275]
### Version

main branch

### Describe what's wrong

run `./gradlew build` failed

### Error message and/or stacktrace

```
> Task :integration-test:test
Current docker context is: orbstack

------------------ Check Docker environment ---------------------
Docker server status ............................................ [running]
mac-docker-connector status ..................................... [stop]
OrbStack status ................................................. [yes]
Using Gravitino IT Docker container to run all integration tests. [embedded test]
-----------------------------------------------------------------
OpenJDK 64-Bit Server VM warning: CodeCache is full. Compiler has been disabled.
CodeCache: size=131072Kb used=48488Kb max_used=48500Kb free=82583Kb
OpenJDK 64-Bit Server VM warning: Try increasing the code cache size using -XX:ReservedCodeCacheSize=
 bounds [0x0000000106ab4000, 0x0000000109a74000, 0x000000010eab4000]
 total_blobs=14298 nmethods=13522 adapters=690
 compilation: disabled (not enough contiguous free space left)

TrinoQueryIT > testSql() FAILED
    java.lang.RuntimeException: Failed to execute test org.opentest4j.AssertionFailedError: Execute sql in the tester jdbc-mysql/00005_catalog.sql under catalog mysql failed.
    Sql:
    call gravitino.system.create_catalog(
        'gt_mysql_xxx1',
        'jdbc-mysql',
        map(
            array['jdbc-url', 'jdbc-user', 'jdbc-password', 'jdbc-driver'],
            array['jdbc:mysql://10.20.31.18:3306/?useSSL=false', 'trino', 'ds123', 'com.mysql.cj.jdbc.Driver']
        )
    );
    Expect:
    <QUERY_FAILED> Catalog test.gt_mysql_xxx1 already exists.
    Actual:
    CALL
        at com.datastrato.gravitino.integration.test.trino.TrinoQueryIT.waitForCompleted(TrinoQueryIT.java:345)
        at com.datastrato.gravitino.integration.test.trino.TrinoQueryIT.testSql(TrinoQueryIT.java:318)

        Caused by:
        java.util.concurrent.ExecutionException: org.opentest4j.AssertionFailedError: Execute sql in the tester jdbc-mysql/00005_catalog.sql under catalog mysql failed.
        Sql:
        call gravitino.system.create_catalog(
            'gt_mysql_xxx1',
            'jdbc-mysql',
            map(
                array['jdbc-url', 'jdbc-user', 'jdbc-password', 'jdbc-driver'],
                array['jdbc:mysql://10.20.31.18:3306/?useSSL=false', 'trino', 'ds123', 'com.mysql.cj.jdbc.Driver']
            )
        );
        Expect:
        <QUERY_FAILED> Catalog test.gt_mysql_xxx1 already exists.
        Actual:
        CALL
            at java.util.concurrent.FutureTask.report(FutureTask.java:122)
            at java.util.concurrent.FutureTask.get(FutureTask.java:192)
            at com.datastrato.gravitino.integration.test.trino.TrinoQueryIT.waitForCompleted(TrinoQueryIT.java:342)
            ... 1 more

            Caused by:
            org.opentest4j.AssertionFailedError: Execute sql in the tester jdbc-mysql/00005_catalog.sql under catalog mysql failed.
            Sql:
            call gravitino.system.create_catalog(
                'gt_mysql_xxx1',
                'jdbc-mysql',
                map(
                    array['jdbc-url', 'jdbc-user', 'jdbc-password', 'jdbc-driver'],
                    array['jdbc:mysql://10.20.31.18:3306/?useSSL=false', 'trino', 'ds123', 'com.mysql.cj.jdbc.Driver']
                )
            );
            Expect:
            <QUERY_FAILED> Catalog test.gt_mysql_xxx1 already exists.
            Actual:
            CALL
                at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
                at org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
                at com.datastrato.gravitino.integration.test.trino.TrinoQueryIT.executeSqlFileWithCheckResult(TrinoQueryIT.java:227)
                at com.datastrato.gravitino.integration.test.trino.TrinoQueryIT.runOneTestSetWithCatalog(TrinoQueryIT.java:114)
                at com.datastrato.gravitino.integration.test.trino.TrinoQueryIT.lambda$runOneTestset$5(TrinoQueryIT.java:367)

232 tests completed, 1 failed, 2 skipped

> Task :integration-test:test FAILED

FAILURE: Build failed with an exception.
```

### How to reproduce

locally run `./gradlew build`

### Additional context

machine: Apple M2 Pro
system: macOS 13.6.1

**Comment by justinmclean** [comment]
I've also seen this issue but have not been able to reliably reproduce it.

**Comment by mchades** [comment]
> I've also seen this issue but have not been able to reliably reproduce it.

It's currently a stable reproduction locally for me, and it fails every time I run the build command
