### ISSUE TITLE
[Bug report] The mysql driver package dependency has been added, but it does not take effect on the existing catalog.

### ISSUE THREAD

**Issue by hanwxx** [datastrato/gravitino#2328]
### Version

main branch

### Describe what's wrong

The mysql driver dependency has been added, the newly added catalog is ok, but the existing mysql catalog still throws exception:
Cannot load JDBC driver class 'com.mysql.jdbc.Driver or com.mysql.cj.jdbc.Driver'

### Error message and/or stacktrace

2024-02-23 15:01:17.691 ERROR [Gravitino-webserver-52] [com.datastrato.gravitino.server.web.rest.ExceptionHandlers$BaseExceptionHandler.handle(ExceptionHandlers.java:257)] - Failed to operate object operation [LIST] under [mysql_business], reason [Cannot load JDBC driver class 'com.mysql.jdbc.Driver or com.mysql.cj.jdbc.Driver']
java.lang.RuntimeException: com.datastrato.gravitino.exceptions.GravitinoRuntimeException: Cannot load JDBC driver class 'com.mysql.jdbc.Driver or com.mysql.cj.jdbc.Driver'
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.doWithCatalog(CatalogOperationDispatcher.java:752) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.listSchemas(CatalogOperationDispatcher.java:103) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.server.web.rest.SchemaOperations.lambda$listSchemas$0(SchemaOperations.java:74) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.lock.TreeLockUtils.doWithTreeLock(TreeLockUtils.java:35) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.server.web.rest.SchemaOperations.lambda$listSchemas$1(SchemaOperations.java:71) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at javax.security.auth.Subject.doAs(Subject.java:422) ~[?:1.8.0_201]
	at com.datastrato.gravitino.utils.PrincipalUtils.doAs(PrincipalUtils.java:25) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.server.web.Utils.doAs(Utils.java:121) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.server.web.rest.SchemaOperations.listSchemas(SchemaOperations.java:66) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at com.datastrato.gravitino.server.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:59) ~[gravitino-server-common-0.5.0-SNAPSHOT.jar:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at com.datastrato.gravitino.server.web.VersioningFilter.doFilter(VersioningFilter.java:94) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[jetty-security-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: com.datastrato.gravitino.exceptions.GravitinoRuntimeException: Cannot load JDBC driver class 'com.mysql.jdbc.Driver or com.mysql.cj.jdbc.Driver'
	at com.datastrato.gravitino.catalog.mysql.converter.MysqlExceptionConverter.toGravitinoException(MysqlExceptionConverter.java:33) ~[?:?]
	at com.datastrato.gravitino.catalog.jdbc.operation.JdbcDatabaseOperations.listDatabases(JdbcDatabaseOperations.java:76) ~[?:?]
	at com.datastrato.gravitino.catalog.jdbc.JdbcCatalogOperations.listSchemas(JdbcCatalogOperations.java:152) ~[?:?]
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.lambda$listSchemas$0(CatalogOperationDispatcher.java:105) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogManager$CatalogWrapper.lambda$doWithSchemaOps$0(CatalogManager.java:88) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.utils.IsolatedClassLoader.withClassLoader(IsolatedClassLoader.java:69) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogManager$CatalogWrapper.doWithSchemaOps(CatalogManager.java:83) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.lambda$listSchemas$1(CatalogOperationDispatcher.java:105) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.doWithCatalog(CatalogOperationDispatcher.java:747) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	... 74 more
Caused by: java.sql.SQLException: Cannot load JDBC driver class 'com.mysql.jdbc.Driver or com.mysql.cj.jdbc.Driver'
	at org.apache.commons.dbcp2.DriverFactory.createDriver(DriverFactory.java:53) ~[?:?]
	at org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:466) ~[?:?]
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:530) ~[?:?]
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:711) ~[?:?]
	at com.datastrato.gravitino.catalog.jdbc.operation.JdbcDatabaseOperations.getConnection(JdbcDatabaseOperations.java:97) ~[?:?]
	at com.datastrato.gravitino.catalog.jdbc.operation.JdbcDatabaseOperations.listDatabases(JdbcDatabaseOperations.java:65) ~[?:?]
	at com.datastrato.gravitino.catalog.jdbc.JdbcCatalogOperations.listSchemas(JdbcCatalogOperations.java:152) ~[?:?]
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.lambda$listSchemas$0(CatalogOperationDispatcher.java:105) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogManager$CatalogWrapper.lambda$doWithSchemaOps$0(CatalogManager.java:88) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.utils.IsolatedClassLoader.withClassLoader(IsolatedClassLoader.java:69) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogManager$CatalogWrapper.doWithSchemaOps(CatalogManager.java:83) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.lambda$listSchemas$1(CatalogOperationDispatcher.java:105) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.doWithCatalog(CatalogOperationDispatcher.java:747) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	... 74 more
Caused by: java.lang.ClassNotFoundException: Class no found com.mysql.jdbc.Driver or com.mysql.cj.jdbc.Driver
	at com.datastrato.gravitino.utils.IsolatedClassLoader$1.loadClass(IsolatedClassLoader.java:158) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
	at org.apache.commons.dbcp2.DriverFactory.createDriver(DriverFactory.java:48) ~[?:?]
	at org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:466) ~[?:?]
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:530) ~[?:?]
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:711) ~[?:?]
	at com.datastrato.gravitino.catalog.jdbc.operation.JdbcDatabaseOperations.getConnection(JdbcDatabaseOperations.java:97) ~[?:?]
	at com.datastrato.gravitino.catalog.jdbc.operation.JdbcDatabaseOperations.listDatabases(JdbcDatabaseOperations.java:65) ~[?:?]
	at com.datastrato.gravitino.catalog.jdbc.JdbcCatalogOperations.listSchemas(JdbcCatalogOperations.java:152) ~[?:?]
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.lambda$listSchemas$0(CatalogOperationDispatcher.java:105) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogManager$CatalogWrapper.lambda$doWithSchemaOps$0(CatalogManager.java:88) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.utils.IsolatedClassLoader.withClassLoader(IsolatedClassLoader.java:69) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogManager$CatalogWrapper.doWithSchemaOps(CatalogManager.java:83) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.lambda$listSchemas$1(CatalogOperationDispatcher.java:105) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.doWithCatalog(CatalogOperationDispatcher.java:747) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	... 74 more
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver or com.mysql.cj.jdbc.Driver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
	at com.datastrato.gravitino.utils.IsolatedClassLoader$1.doLoadClass(IsolatedClassLoader.java:175) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.utils.IsolatedClassLoader$1.loadClass(IsolatedClassLoader.java:156) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
	at org.apache.commons.dbcp2.DriverFactory.createDriver(DriverFactory.java:48) ~[?:?]
	at org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:466) ~[?:?]
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:530) ~[?:?]
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:711) ~[?:?]
	at com.datastrato.gravitino.catalog.jdbc.operation.JdbcDatabaseOperations.getConnection(JdbcDatabaseOperations.java:97) ~[?:?]
	at com.datastrato.gravitino.catalog.jdbc.operation.JdbcDatabaseOperations.listDatabases(JdbcDatabaseOperations.java:65) ~[?:?]
	at com.datastrato.gravitino.catalog.jdbc.JdbcCatalogOperations.listSchemas(JdbcCatalogOperations.java:152) ~[?:?]
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.lambda$listSchemas$0(CatalogOperationDispatcher.java:105) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogManager$CatalogWrapper.lambda$doWithSchemaOps$0(CatalogManager.java:88) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.utils.IsolatedClassLoader.withClassLoader(IsolatedClassLoader.java:69) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogManager$CatalogWrapper.doWithSchemaOps(CatalogManager.java:83) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.lambda$listSchemas$1(CatalogOperationDispatcher.java:105) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogOperationDispatcher.doWithCatalog(CatalogOperationDispatcher.java:747) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	... 74 more

### How to reproduce

version: 0.5.0-SNAPSHOT

Step1 Create a mysql catalog:mysql_business in WEB UI, When clicking catalog, an exception is thrown:
Cannot load JDBC driver class 'com.mysql.jdbc.Driver or com.mysql.cj.jdbc.Driver'
![screenshot-20240223-150919](https://github.com/datastrato/gravitino/assets/160711189/76222872-3df9-4e42-9bc5-9c1bbb33447c)

Step2 Add MySQL JDBC driver to the catalogs/jdbc-mysql/libs directory，and restart  gravitino；

Step3 Create a new mysql catalog: mysql_business01, Exception disappeared：
![screenshot-20240223-150950](https://github.com/datastrato/gravitino/assets/160711189/25fafb65-e078-4753-adc2-81af59602582)

Step4 Clicking the existed catalog:mysql_business , still throws exception:
Cannot load JDBC driver class 'com.mysql.jdbc.Driver or com.mysql.cj.jdbc.Driver'。
![screenshot-20240223-151043](https://github.com/datastrato/gravitino/assets/160711189/c83d6d59-956c-4af9-8957-20a0b697fc2e)

**Comment by yuqi1129** [comment]
@Clearvive 
Please help to take a look, thanks.

**Comment by yuqi1129** [comment]
@hanwxx I can't reproduce it locally. Do I miss anything?

**Comment by FANNG1** [comment]
seems Jdbc driver are not loaded correctly, @hanwxx could you help to verify:
1. what's the driver name when you create MySQL catalog?
2. what's the package name of MySQL JDBC driver?
