### ISSUE TITLE
[Bug report] TrinoConnectorIT fails to initialize properly.

### ISSUE THREAD

**Issue by charliecheng630** [datastrato/gravitino#2459]
### Version

main branch

### Describe what's wrong

The initialization of TrinoConnectorIT fails, even when I increase the sleep time and retry limits.

### Error message and/or stacktrace

```
java.lang.RuntimeException: java.sql.SQLException: Query failed (#20240307_113902_00026_8g6sz): line 1:1: Catalog 'trinoit_metalake_650b2387.trinoit_catalog_0fa21da2' does not exist
	at com.datastrato.gravitino.integration.test.container.TrinoContainer.executeUpdateSQL(TrinoContainer.java:183)
	at com.datastrato.gravitino.integration.test.trino.TrinoConnectorIT.createSchema(TrinoConnectorIT.java:150)
	at com.datastrato.gravitino.integration.test.trino.TrinoConnectorIT.startDockerContainer(TrinoConnectorIT.java:110)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at 
```

### How to reproduce

The following is my environment.
```
------------------------------------------------------------
Gradle 8.2
------------------------------------------------------------

Build time:   2023-06-30 18:02:30 UTC
Revision:     5f4a070a62a31a17438ac998c2b849f4f6892877

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.10 (Homebrew 17.0.10+0)
OS:           Mac OS X 14.1 aarch64
```

OrbStack configuration and resources
```
cpu: 8
docker.node_name: orbstack
docker.set_context: true
k8s.enable: false
k8s.expose_services: false
machine.docker.username: yuchen
memory_mib: 8192
mount_hide_shared: false
network.https: true
network_bridge: true
network_proxy: auto
rosetta: true
setup.use_admin: true
ssh.expose_port: false
```

My execution command:
```
git checkout v0.4.0
./gradlew clean
./gradlew build
```

I assign the sleepTime=50000  and  retryLimit=24 for starting container services in method [checkSyncCatalogFromGravitino](https://github.com/datastrato/gravitino/blob/main/integration-test/src/test/java/com/datastrato/gravitino/integration/test/container/TrinoContainer.java#L115) and [checkContainerStatus](https://github.com/datastrato/gravitino/blob/main/integration-test/src/test/java/com/datastrato/gravitino/integration/test/container/TrinoContainer.java#L68),  and I also increase memory and cpu for docker resources, but this integration test still fails.

<img width="2009" alt="Screenshot 2024-03-07 at 10 06 09 PM" src="https://github.com/datastrato/gravitino/assets/74488612/5049d3cc-4f6b-4e0c-addb-9876568fb04f">

**Comment by charliecheng630** [comment]
[integration-test.log](https://github.com/datastrato/gravitino/files/14525274/integration-test.log)
the complete log is attached here for reference.

**Comment by jerryshao** [comment]
@diqiu50 , would you please help to check this issue?

**Comment by diqiu50** [comment]
@charliecheng630 
It seems your network environment is unexpected for our code.
Can you execute ifconfig on your machine, and give me the output.

**Comment by diqiu50** [comment]
n the current solution, we obtain the host IP address to enable container access to the host network. The method for obtaining the IP address involves using commands like ifconfig. On a Mac, we retrieve the IP of the en0 device. If your network device does not have an en0, it returns 127.0.0.1. This address cannot be used by the container to access the host network.

**Comment by charliecheng630** [comment]
> @charliecheng630 It seems your network environment is unexpected for our code. Can you execute the `ifconfig` command on your machine, and give me the output.

@diqiu50 ifconfig output:
```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
anpi0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether ce:3e:80:53:ee:9a
	media: none
	status: inactive
anpi1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether ce:3e:80:53:ee:9b
	media: none
	status: inactive
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=50b<RXCSUM,TXCSUM,VLAN_HWTAGGING,AV,CHANNEL_IO>
	ether 10:b9:c4:76:1e:db
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (none)
	status: inactive
en4: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether ce:3e:80:53:ee:7a
	nd6 options=201<PERFORMNUD,DAD>
	media: none
	status: inactive
en5: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether ce:3e:80:53:ee:7b
	nd6 options=201<PERFORMNUD,DAD>
	media: none
	status: inactive
en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 36:08:55:95:f5:40
	media: autoselect <full-duplex>
	status: inactive
en3: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 36:08:55:95:f5:44
	media: autoselect <full-duplex>
	status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 36:08:55:95:f5:40
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 9 priority 0 path cost 0
	member: en3 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 10 priority 0 path cost 0
	nd6 options=201<PERFORMNUD,DAD>
	media: <unknown type>
	status: inactive
ap1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=6460<TSO4,TSO6,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
	ether 32:b9:c4:75:36:cf
	inet6 fe80::30b9:c4ff:fe75:36cf%ap1 prefixlen 64 scopeid 0xc 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (<unknown type>)
	status: inactive
en1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=6460<TSO4,TSO6,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
	ether 10:b9:c4:75:36:cf
	inet6 fe80::42c:6f31:410e:71a4%en1 prefixlen 64 secured scopeid 0xd 
	inet 192.168.16.11 netmask 0xffffff00 broadcast 192.168.16.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
awdl0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=6460<TSO4,TSO6,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
	ether fe:9e:6c:22:6d:c0
	inet6 fe80::fc9e:6cff:fe22:6dc0%awdl0 prefixlen 64 scopeid 0xe 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
llw0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether fe:9e:6c:22:6d:c0
	inet6 fe80::fc9e:6cff:fe22:6dc0%llw0 prefixlen 64 scopeid 0xf 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: inactive
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet6 fe80::70aa:b05:44ab:41cc%utun0 prefixlen 64 scopeid 0x10 
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::55d7:38c2:8a76:fd81%utun1 prefixlen 64 scopeid 0x11 
	nd6 options=201<PERFORMNUD,DAD>
utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::9655:52f8:1997:60d4%utun2 prefixlen 64 scopeid 0x12 
	nd6 options=201<PERFORMNUD,DAD>
utun3: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1000
	inet6 fe80::ce81:b1c:bd2c:69e%utun3 prefixlen 64 scopeid 0x13 
	nd6 options=201<PERFORMNUD,DAD>
vmenet0: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=60<TSO4,TSO6>
	ether 2e:81:8f:43:33:32
	media: autoselect
	status: active
bridge100: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 12:b9:c4:67:3a:64
	inet 198.19.249.3 netmask 0xffffff00 broadcast 198.19.249.255
	inet6 fe80::10b9:c4ff:fe67:3a64%bridge100 prefixlen 64 scopeid 0x15 
	inet6 fd07:b51a:cc66:0:a617:db5e:ab7:e9f1 prefixlen 64 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x0
	member: vmenet0 flags=10003<LEARNING,DISCOVER,CSUM>
	        ifmaxaddr 0 port 20 priority 0 path cost 0
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active

```

**Comment by diqiu50** [comment]
@charliecheng630 I have already fixed the issue. You can try it now.

**Comment by diqiu50** [comment]
Your primary network device's name is en1, not en0 as we expected.
···
en1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=6460<TSO4,TSO6,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
	ether 10:b9:c4:75:36:cf
	inet6 fe80::42c:6f31:410e:71a4%en1 prefixlen 64 secured scopeid 0xd 
	inet 192.168.16.11 netmask 0xffffff00 broadcast 192.168.16.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
···

**Comment by charliecheng630** [comment]
@diqiu50 I executed the command   `./gradlew build ` successfully. 
Thank you all for your supports.
