### ISSUE TITLE
[Bug report] Tests in TrinoConnectorIT fail on mac with Docker Desktop

### ISSUE THREAD

**Issue by zivali** [datastrato/gravitino#2598]
### Version

main branch

### Describe what's wrong

Two tests in TrinoConnectorIT fail on Mac with Docker Desktop during build. But running with OrbStack, those two tests won't fail.
- TrinoConnectorIT > testIcebergTableAndSchemaCreatedByGravitino()
- TrinoConnectorIT > testScenarioJoinTwoTable()

### Error message and/or stacktrace

```
TrinoConnectorIT > testIcebergTableAndSchemaCreatedByGravitino() FAILED
    org.opentest4j.AssertionFailedError: Trino fail to load table created by gravitino: show create table "trinoit_metalake_0cac2a87.catalog_1563988a".schema_3050445e.table_6ab8e036
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
        at org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
        at com.datastrato.gravitino.integration.test.trino.TrinoConnectorIT.testIcebergTableAndSchemaCreatedByGravitino(TrinoConnectorIT.java:979)



TrinoConnectorIT > testScenarioJoinTwoTable() FAILED
    java.lang.RuntimeException: java.sql.SQLException: Query failed (#20240319_131708_00201_mya4a): java.net.URISyntaxException: Illegal character in hostname at index 16: hdfs://nostalgic_bell.407f45c1-6aa8-4300-90be-13e89b5f8ed7:9000
        at com.datastrato.gravitino.integration.test.container.TrinoContainer.executeUpdateSQL(TrinoContainer.java:188)
        at com.datastrato.gravitino.integration.test.trino.TrinoConnectorIT.testScenarioTable1(TrinoConnectorIT.java:279)
        at com.datastrato.gravitino.integration.test.trino.TrinoConnectorIT.testScenarioJoinTwoTable(TrinoConnectorIT.java:352)

        Caused by:
        java.sql.SQLException: Query failed (#20240319_131708_00201_mya4a): java.net.URISyntaxException: Illegal character in hostname at index 16: hdfs://nostalgic_bell.407f45c1-6aa8-4300-90be-13e89b5f8ed7:9000
            at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)
            at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:294)
            at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:254)
            at io.trino.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
            at io.trino.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
            at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
            at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:295)
            at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:207)
            at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:162)
            at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:301)
            at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
            at io.trino.jdbc.TrinoResultSet$AsyncIterator.lambda$new$1(TrinoResultSet.java:179)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:750)

            Caused by:
            java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in hostname at index 16: hdfs://nostalgic_bell.407f45c1-6aa8-4300-90be-13e89b5f8ed7:9000
                at org.apache.hadoop.net.NetUtils.getCanonicalUri(NetUtils.java:337)
                at org.apache.hadoop.hdfs.DistributedFileSystem.canonicalizeUri(DistributedFileSystem.java:2029)
                at org.apache.hadoop.fs.FileSystem.getCanonicalUri(FileSystem.java:384)
                at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:805)
                at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:254)
                at org.apache.hadoop.hdfs.DistributedFileSystem$54.doCall(DistributedFileSystem.java:2750)
                at org.apache.hadoop.hdfs.DistributedFileSystem$54.doCall(DistributedFileSystem.java:2747)
                at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
                at org.apache.hadoop.hdfs.DistributedFileSystem.getEZForPath(DistributedFileSystem.java:2766)
                at io.trino.plugin.hive.util.HiveWriteUtils.isHdfsEncrypted(HiveWriteUtils.java:516)
                at io.trino.plugin.hive.HiveLocationService.shouldUseTemporaryDirectory(HiveLocationService.java:118)
                at io.trino.plugin.hive.HiveLocationService.forExistingTable(HiveLocationService.java:97)
                at io.trino.plugin.hive.HiveMetadata.beginInsertOrMerge(HiveMetadata.java:2089)
                at io.trino.plugin.hive.HiveMetadata.beginInsert(HiveMetadata.java:2048)
                at io.trino.plugin.hive.HiveMetadata.beginInsert(HiveMetadata.java:327)
                at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.beginInsert(ClassLoaderSafeConnectorMetadata.java:573)
                at com.datastrato.gravitino.trino.connector.GravitinoMetadata.beginInsert(GravitinoMetadata.java:221)
                at io.trino.tracing.TracingConnectorMetadata.beginInsert(TracingConnectorMetadata.java:646)
                at io.trino.metadata.MetadataManager.beginInsert(MetadataManager.java:1071)
                at io.trino.tracing.TracingMetadata.beginInsert(TracingMetadata.java:647)
                at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:253)
                at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:188)
                at io.trino.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:106)
                at io.trino.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:105)
                at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:81)
                at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:72)
                at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
                at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:72)
                at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:37)
                at io.trino.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:21)
                at io.trino.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
                at io.trino.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
                at io.trino.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:31)
                at io.trino.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:91)
                at io.trino.sql.planner.LogicalPlanner.runOptimizer(LogicalPlanner.java:300)
                at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:270)
                at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:239)
                at io.trino.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:234)
                at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:482)
                at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:462)
                at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:400)
                at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:256)
                at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
                at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
                at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:568)
                at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:543)
                at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
                at io.trino.$gen.Trino_426____20240319_131428_2.run(Unknown Source)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
                at java.base/java.lang.Thread.run(Thread.java:833)

                Caused by:
                java.net.URISyntaxException: Illegal character in hostname at index 16: hdfs://nostalgic_bell.407f45c1-6aa8-4300-90be-13e89b5f8ed7:9000
                    at java.base/java.net.URI$Parser.fail(URI.java:2976)
                    at java.base/java.net.URI$Parser.parseHostname(URI.java:3511)
                    at java.base/java.net.URI$Parser.parseServer(URI.java:3360)
                    at java.base/java.net.URI$Parser.parseAuthority(URI.java:3279)
                    at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3221)
                    at java.base/java.net.URI$Parser.parse(URI.java:3177)
                    at java.base/java.net.URI.<init>(URI.java:708)
                    at org.apache.hadoop.net.NetUtils.getCanonicalUri(NetUtils.java:335)
                    ... 50 more
<==========---> 84% EXECUTING [8m 34s]

> :integration-test:test > Executing test com.datastrato.gravitino.integration.test.trino.TrinoQueryIT
> :integration-test:test > 43 tests completed, 2 failed

```

### How to reproduce

Run `./gradlew clean` `./gradlew build` on mac with Docker Desktop.

```
➤ ./gradlew --version

------------------------------------------------------------
Gradle 8.2
------------------------------------------------------------

Build time:   2023-06-30 18:02:30 UTC
Revision:     5f4a070a62a31a17438ac998c2b849f4f6892877

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          1.8.0_352 (Azul Systems, Inc. 25.352-b08)
OS:           Mac OS X 14.2.1 aarch64
```
Docker Desktop version: 4.27.2 (137060)

**Comment by jerryshao** [comment]
CC @yuqi1129 @diqiu50 please help to check.

**Comment by diqiu50** [comment]
@zivali 
When you are running on Docker Desktop, did you start the script `dev/docker/tools/mac-docker-connector.sh`?

**Comment by zivali** [comment]
@diqiu50 Hi, yes I have the script running when testing. Here's relevant log:
```
> Configure project :
Current docker context is: desktop-linux

------------------ Check Docker environment ---------------------
Docker server status ............................................ [running]
mac-docker-connector status ..................................... [running]
OrbStack status ................................................. [no]
Using Gravitino IT Docker container to run all integration tests. [embedded test]
-----------------------------------------------------------------
```

**Comment by yuqi1129** [comment]
is `nostalgic_bell.407f45c1-6aa8-4300-90be-13e89b5f8ed7` your local host name? can you paste your `hosts` files also?

**Comment by diqiu50** [comment]
It seems the HDFS client resolves the IP address to an invalid domain name.

Can you update your code to run it again?
`integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java`
![1710917208474](https://github.com/datastrato/gravitino/assets/7985733/f5a3dd81-8fbf-4e05-ae0f-3fd07d9f2f51)

**Comment by diqiu50** [comment]
Yes.

**Comment by zivali** [comment]
Sure! I will open a PR for this.
