### ISSUE TITLE
[Bug report] TrinoQueryIT is not very stable and fails on `lakehouse-iceberg/00007_varchar.sql` often

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#2633]
### Version

main branch

### Describe what's wrong

Please refer to 
https://github.com/datastrato/gravitino/actions/runs/8384634070/job/22962267325?pr=2632

### Error message and/or stacktrace

TrinoQueryIT > testSql() FAILED
    java.lang.RuntimeException: Failed to execute test org.opentest4j.AssertionFailedError: Execute sql in the tester lakehouse-iceberg/00007_varchar.sql under catalog iceberg failed.
    Sql:
    CREATE SCHEMA "test.gt_iceberg".varchar_db1;
    Expect:
    CREATE SCHEMA
    Actual:
    Query 20240322_024444_00493_vvbbs failed: line 1:1: Schema 'test.gt_iceberg.varchar_db1' already exists
    LINE 1: CREATE SCHEMA "test.gt_iceberg".varchar_db1
            ^
        at com.datastrato.gravitino.integration.test.trino.TrinoQueryIT.waitForCompleted(TrinoQueryIT.java:347)
        at com.datastrato.gravitino.integration.test.trino.TrinoQueryIT.testSql(TrinoQueryIT.java:320)

        Caused by:
        java.util.concurrent.ExecutionException: org.opentest4j.AssertionFailedError: Execute sql in the tester lakehouse-iceberg/00007_varchar.sql under catalog iceberg failed.
        Sql:
        CREATE SCHEMA "test.gt_iceberg".varchar_db1;
        Expect:
        CREATE SCHEMA
        Actual:
        Query 20240322_024444_00493_vvbbs failed: line 1:1: Schema 'test.gt_iceberg.varchar_db1' already exists
        LINE 1: CREATE SCHEMA "test.gt_iceberg".varchar_db1
                ^
            at java.util.concurrent.FutureTask.report(FutureTask.java:122)
            at java.util.concurrent.FutureTask.get(FutureTask.java:192)
            at com.datastrato.gravitino.integration.test.trino.TrinoQueryIT.waitForCompleted(TrinoQueryIT.java:344)
            ... 1 more

            Caused by:
            org.opentest4j.AssertionFailedError: Execute sql in the tester lakehouse-iceberg/00007_varchar.sql under catalog iceberg failed.
            Sql:
            CREATE SCHEMA "test.gt_iceberg".varchar_db1;
            Expect:
            CREATE SCHEMA
            Actual:
            Query 20240322_024444_00493_vvbbs failed: line 1:1: Schema 'test.gt_iceberg.varchar_db1' already exists
            LINE 1: CREATE SCHEMA "test.gt_iceberg".varchar_db1
                    ^
                at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
                at org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
                at com.datastrato.gravitino.integration.test.trino.TrinoQueryIT.executeSqlFileWithCheckResult(TrinoQueryIT.java:228)
                at com.datastrato.gravitino.integration.test.trino.TrinoQueryIT.runOneTestSetWithCatalog(TrinoQueryIT.java:115)
                at com.datastrato.gravitino.integration.test.trino.TrinoQueryIT.lambda$runOneTestset$5(TrinoQueryIT.java:369)

49 tests completed, 1 failed, 1 skipped

### How to reproduce

Please see above

### Additional context

The integration log files seem to be missing in CI, perhaps we should also handle it.

**Comment by yuqi1129** [comment]
@diqiu50 
I suspect the root cause is that the Iceberg catalog uses Hive as the backend and The Hive backend already has the schema.
