### ISSUE TITLE
[Bug report] A problem occurred starting process 'command 'python'

### ISSUE THREAD

**Issue by yuqi1129** [datastrato/gravitino#2719]
### Version

main branch

### Describe what's wrong

Please see below.

### Error message and/or stacktrace

```text
> Task :clients:client-python:pythonVersion FAILED

Build gravitino FAILURE reason:                                
    Execution failed for task ':clients:client-python:pythonVersion':
        org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'python''
            at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
            at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
            at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:370)
            at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
            at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
            at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
            at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
            Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'python'
                at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
                at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
                at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
                at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
                ... 3 more
                Caused by: java.io.IOException: Cannot run program "python" (in directory "/Users/yuqi/project/gravitino/clients/client-python"): error=2, No such file or directory
                    at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
                    ... 6 more
                    Caused by: java.io.IOException: error=2, No such file or directory
                        ... 7 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clients:client-python:pythonVersion'.
> A problem occurred starting process 'command 'python''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 648ms
33 actionable tasks: 13 executed, 1 from cache, 19 up-to-date

```

### How to reproduce

./gradlew test -PskipITs -PskipWebITs

```shell
➜  [/Users/yuqi/project/gravitino] git:(main) python --version
zsh: command not found: python
➜  [/Users/yuqi/project/gravitino] git:(main) python3 --version
Python 3.9.6
```

**Comment by shaofengshi** [comment]
I encounter the same problem, although I already installed Python 3.12 with homebrew:

<img width="1420" alt="image" src="https://github.com/datastrato/gravitino/assets/5411805/8034b158-c22b-4873-b16a-7677cc9b9d06">

Even if I change the "python" to "python3" (Mac build-in with /usr/bin/python3) from the build.gradle.kts, it still reports "pytest" not found:

<img width="1411" alt="image" src="https://github.com/datastrato/gravitino/assets/5411805/02dfa005-77cb-44b3-8d16-547aece0180f">

**Comment by jerryshao** [comment]
This is already fixed.
