### ISSUE TITLE
[Bug report] Cannot run program "python" (in directory "gravitino/clients/client-python")

### ISSUE THREAD

**Issue by charliecheng630** [datastrato/gravitino#2729]
### Version

main branch

### Describe what's wrong

`./gradlew build` failed.

### Error message and/or stacktrace

```
> Configure project :
checkContainerRunning command execution failed: Process 'command 'bash'' finished with non-zero exit value 1
Current docker context is: orbstack

------------------ Check Docker environment ---------------------
Docker server status ............................................ [running]
mac-docker-connector status ..................................... [stop]
OrbStack status ................................................. [yes]
Using Gravitino IT Docker container to run all integration tests. [embedded test]
-----------------------------------------------------------------

> Configure project :web
Kotlin DSL property assignment is an incubating feature.

> Task :clients:client-python:pythonVersion FAILED

Build gravitino FAILURE reason:                                
    Execution failed for task ':clients:client-python:pythonVersion':
        org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'python''
            at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:241)
            at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:218)
            at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:370)
            at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
            at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
            at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
            at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
            Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'python'
                at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
                at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
                at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
                at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
                ... 3 more
                Caused by: java.io.IOException: Cannot run program "python" (in directory "/Users/yuchen/IdeaProjects/gravitino/clients/client-python"): error=2, No such file or directory
                    at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
                    ... 6 more
                    Caused by: java.io.IOException: error=2, No such file or directory
                        ... 7 more


FAILURE: Build failed with an exception.

```

### How to reproduce

The following is my environment.

```
------------------------------------------------------------
Gradle 8.2
------------------------------------------------------------

Build time:   2023-06-30 18:02:30 UTC
Revision:     5f4a070a62a31a17438ac998c2b849f4f6892877

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.10 (Homebrew 17.0.10+0)
OS:           Mac OS X 14.1 aarch64
```

python --version
`Python 2.7.18`

python3 --version
`Python 3.9.6`

**Comment by charliecheng630** [comment]
After I pulled the commit （40eef72d）, it worked successfully.
Thanks for your supports. @shaofengshi @yuqi1129
