### ISSUE TITLE
[Bug report] bucket and truncate are missing width params in Gravitino SortOrder

### ISSUE THREAD

**Issue by caican00** [datastrato/gravitino#2921]
### Version

main branch

### Describe what's wrong

bucket and truncate are missing width params in Gravitino SortOrder, as shown in the following picture:
![image](https://github.com/datastrato/gravitino/assets/94670132/b36bd39b-c622-46c9-afb5-f55f1ed33146)

### Error message and/or stacktrace

None

### How to reproduce

None

**Comment by FANNG1** [comment]
could you provide more context about why should we add `bucket` and `truncate` to SortOrder?  I'm also confused about the picture about the content.  cc @yuqi1129

**Comment by FANNG1** [comment]
@caican00 could you provider more information here?

**Comment by caican00** [comment]
> @caican00 could you provide more information here?



> could you provide more context about why should we add `bucket` and `truncate` to SortOrder? I'm also confused about the picture about the content. cc @yuqi1129

SortOrder in Iceberg supports FunctionExpression, such as `year`, `month`, `bucket`, `truncate`, etc.
truncate and bucket functions both have two parameters, such as `bucket(10, col1)`, `truncate(2, col2)`.

However, in gravitino, when converting an iceberg sortorder with `bucket` or `truncate` to gravitino sortOrder, there is only one parameter in `bucket` and `truncate` functions.

This picture shows the details of the parameters of the `bucket` and `truncate` functions in gravitino sortorder, we can test it in `com.datastrato.gravitino.catalog.lakehouse.iceberg.converter.TestFromIcebergSortOrder#testFromSortOrder`
![image](https://github.com/datastrato/gravitino/assets/94670132/0bffa655-f40b-4242-a05c-358a6651e4ee)

And if we want to convert the gravitino sortOrder with `bucket` or `truncate` to iceberg sortOrder, we will get the following error:
```

java.lang.IllegalArgumentException: Bucket sort should have 2 arguments

	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
	at com.datastrato.gravitino.catalog.lakehouse.iceberg.converter.ToIcebergSortOrder.toSortOrder(ToIcebergSortOrder.java:56)
	at com.datastrato.gravitino.catalog.lakehouse.iceberg.converter.TestFromIcebergSortOrder.testFromSortOrder(TestFromIcebergSortOrder.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)

```

**Comment by caican00** [comment]
@FANNG1 @yuqi1129 I added some detailed information about the issue. If I missed anything, please point it out. Thank you

**Comment by caican00** [comment]
> > @caican00 could you provide more information here?
> 
> > could you provide more context about why should we add `bucket` and `truncate` to SortOrder? I'm also confused about the picture about the content. cc @yuqi1129
> 
> SortOrder in Iceberg supports FunctionExpression, such as `year`, `month`, `bucket`, `truncate`, etc. truncate and bucket functions both have two parameters, such as `bucket(10, col1)`, `truncate(2, col2)`.
> 
> However, in gravitino, when converting an iceberg sortorder with `bucket` or `truncate` to gravitino sortOrder, there is only one parameter in `bucket` and `truncate` functions.
> 
> This picture shows the details of the parameters of the `bucket` and `truncate` functions in gravitino sortorder, we can test it in `com.datastrato.gravitino.catalog.lakehouse.iceberg.converter.TestFromIcebergSortOrder#testFromSortOrder` ![image](https://private-user-images.githubusercontent.com/94670132/323596723-0bffa655-f40b-4242-a05c-358a6651e4ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTMxNTEsIm5iZiI6MTcxMzQ5Mjg1MSwicGF0aCI6Ii85NDY3MDEzMi8zMjM1OTY3MjMtMGJmZmE2NTUtZjQwYi00MjQyLWEwNWMtMzU4YTY2NTFlNGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAyMTQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxOWQzNjMyZmY4ZTU5MWI2N2VhYzRkMTI2ZTFiNDgyZTE2ZDlmNjVhYzJiZmM1MjdmMTZjYWVjYzBkYjJlYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ob94-jz2YIyRPAtErzk1D696f9rhdtN-AtUele5BRjo)
> 
> And if we want to convert the gravitino sortOrder with `bucket` or `truncate` to iceberg sortOrder, we will get the following error as the first param is missing.
> 
> ```
> 
> java.lang.IllegalArgumentException: Bucket sort should have 2 arguments
> 
> 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
> 	at com.datastrato.gravitino.catalog.lakehouse.iceberg.converter.ToIcebergSortOrder.toSortOrder(ToIcebergSortOrder.java:56)
> 	at com.datastrato.gravitino.catalog.lakehouse.iceberg.converter.TestFromIcebergSortOrder.testFromSortOrder(TestFromIcebergSortOrder.java:86)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
> 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
> ```

@FANNG1 may i ask there is anything else I need to provide?

**Comment by FANNG1** [comment]
ok, I got the context, will review it later.
