### ISSUE TITLE
[Bug report] Dead lock issue in performance test environment (100 concurrency)

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#2998]
### Version

main branch

### Describe what's wrong

<img width="1834" alt="image" src="https://github.com/datastrato/gravitino/assets/154112360/4864c9d8-1259-4f09-8baf-a46388045f2e">

### Error message and/or stacktrace

root@ip-172-31-4-61:~/gravitino/logs# cat gravitino-server_20240417.log | head -10
2024-04-17 11:07:19.275 WARN [tree-lock-dead-lock-checker-0] [com.datastrato.gravitino.lock.LockManager.lambda$checkDeadLock$1(LockManager.java:124)] - Dead lock detected for thread Thread[Gravitino-webserver-131,5,main] on node TreeLockNode{ident=pm,hashCode=3612}, threads that holding the node: {Thread[Gravitino-webserver-126,5,main]=1713348022031, Thread[Gravitino-webserver-67,5,main]=1713347807112, Thread[Gravitino-webserver-96,5,main]=1713347843761, Thread[Gravitino-webserver-77,5,main]=1713347736031, Thread[Gravitino-webserver-169,5,main]=1713349251210, Thread[Gravitino-webserver-74,5,main]=1713347805031, Thread[Gravitino-webserver-172,5,main]=1713349251238, Thread[Gravitino-webserver-68,5,main]=1713347682347, Thread[Gravitino-webserver-28,5,main]=1713347718135, Thread[Gravitino-webserver-99,5,main]=1713347876536, Thread[Gravitino-webserver-44,5,main]=1713347696217, Thread[Gravitino-webserver-75,5,main]=1713347716747, Thread[Gravitino-webserver-124,5,main]=1713348050657, Thread[Gravitino-webserver-81,5,main]=1713347745940, Thread[Gravitino-webserver-43,5,main]=1713347638721, Thread[Gravitino-webserver-34,5,main]=1713347745023, Thread[Gravitino-webserver-135,5,main]=1713348087562, Thread[Gravitino-webserver-107,5,main]=1713347911641, Thread[Gravitino-webserver-76,5,main]=1713347810108, Thread[Gravitino-webserver-66,5,main]=1713347664952, Thread[Gravitino-webserver-84,5,main]=1713347803481, Thread[Gravitino-webserver-141,5,main]=1713348122536, Thread[Gravitino-webserver-140,5,main]=1713348121540, Thread[Gravitino-webserver-45,5,main]=1713347801714, Thread[Gravitino-webserver-100,5,main]=1713347877538, Thread[Gravitino-webserver-111,5,main]=1713347913540, Thread[Gravitino-webserver-162,5,main]=1713349315874, Thread[Gravitino-webserver-120,5,main]=1713347983550, Thread[Gravitino-webserver-73,5,main]=1713347696184, Thread[Gravitino-webserver-85,5,main]=1713347804112, Thread[Gravitino-webserver-69,5,main]=1713347807993, Thread[Gravitino-webserver-115,5,main]=1713347951818, Thread[Gravitino-webserver-30,5,main]=1713347639631, Thread[Gravitino-webserver-90,5,main]=1713347839537, Thread[Gravitino-webserver-63,5,main]=1713347801665, Thread[Gravitino-webserver-92,5,main]=1713347808548, Thread[Gravitino-webserver-86,5,main]=1713347775771, Thread[Gravitino-webserver-125,5,main]=1713348016733, Thread[Gravitino-webserver-46,5,main]=1713347841540, Thread[Gravitino-webserver-26,5,main]=1713347846840, Thread[Gravitino-webserver-150,5,main]=1713349250221, Thread[Gravitino-webserver-110,5,main]=1713347947526, Thread[Gravitino-webserver-114,5,main]=1713347947536, Thread[Gravitino-webserver-79,5,main]=1713347806200, Thread[Gravitino-webserver-173,5,main]=1713349315869, Thread[Gravitino-webserver-103,5,main]=1713347909540, Thread[Gravitino-webserver-132,5,main]=1713348053536, Thread[Gravitino-webserver-129,5,main]=1713348054575, Thread[Gravitino-webserver-95,5,main]=1713347848896, Thread[Gravitino-webserver-80,5,main]=1713347802718, Thread[Gravitino-webserver-138,5,main]=1713348088746, Thread[Gravitino-webserver-40,5,main]=1713347717378, Thread[Gravitino-webserver-139,5,main]=1713348094022, Thread[Gravitino-webserver-91,5,main]=1713347812989, Thread[Gravitino-webserver-128,5,main]=1713348058999, Thread[Gravitino-webserver-144,5,main]=1713348155537, Thread[Gravitino-webserver-62,5,main]=1713347692877, Thread[Gravitino-webserver-61,5,main]=1713347638720, Thread[Gravitino-webserver-89,5,main]=1713347811766, Thread[Gravitino-webserver-127,5,main]=1713348085661, Thread[Gravitino-webserver-109,5,main]=1713347915723, Thread[Gravitino-webserver-48,5,main]=1713347801005, Thread[Gravitino-webserver-41,5,main]=1713347801536, Thread[Gravitino-webserver-94,5,main]=1713347808215, Thread[Gravitino-webserver-136,5,main]=1713348119537, Thread[Gravitino-webserver-37,5,main]=1713347802016, Thread[Gravitino-webserver-33,5,main]=1713347718135, Thread[Gravitino-webserver-104,5,main]=1713347910680, Thread[Gravitino-webserver-122,5,main]=1713348024036, Thread[Gravitino-webserver-117,5,main]=1713347980642, Thread[Gravitino-webserver-116,5,main]=1713347979537, Thread[Gravitino-webserver-134,5,main]=1713348086536, Thread[Gravitino-webserver-83,5,main]=1713347777299, Thread[Gravitino-webserver-98,5,main]=1713347875818, Thread[Gravitino-webserver-36,5,main]=1713347801491, Thread[Gravitino-webserver-121,5,main]=1713348015647, Thread[Gravitino-webserver-82,5,main]=1713347810021, Thread[Gravitino-webserver-171,5,main]=1713349325025, Thread[Gravitino-webserver-97,5,main]=1713347880980, Thread[Gravitino-webserver-133,5,main]=1713348154539, Thread[Gravitino-webserver-25,5,main]=1713347616305, Thread[Gravitino-webserver-102,5,main]=1713347885171, Thread[Gravitino-webserver-47,5,main]=1713347700648, Thread[Gravitino-webserver-70,5,main]=1713347801442, Thread[Gravitino-webserver-38,5,main]=1713347805122, Thread[Gravitino-webserver-146,5,main]=1713348156537, Thread[Gravitino-webserver-78,5,main]=1713347744174, Thread[Gravitino-webserver-88,5,main]=1713347777296, Thread[Gravitino-webserver-42,5,main]=1713347618814, Thread[Gravitino-webserver-39,5,main]=1713347693665, Thread[Gravitino-webserver-72,5,main]=1713347693666, Thread[Gravitino-webserver-29,5,main]=1713347806573, Thread[Gravitino-webserver-118,5,main]=1713347982536, Thread[Gravitino-webserver-123,5,main]=1713348014539, Thread[Gravitino-webserver-65,5,main]=1713347716733, Thread[Gravitino-webserver-147,5,main]=1713348157539, Thread[Gravitino-webserver-35,5,main]=1713347804013, Thread[Gravitino-webserver-105,5,main]=1713347945652, Thread[Gravitino-webserver-142,5,main]=1713348123540, Thread[Gravitino-webserver-32,5,main]=1713347801569, Thread[Gravitino-webserver-113,5,main]=1713347981668, Thread[Gravitino-webserver-145,5,main]=1713348127199, Thread[Gravitino-webserver-31,5,main]=1713347666760, Thread[Gravitino-webserver-131,5,main]=1713348052539, Thread[Gravitino-webserver-112,5,main]=1713347946538, Thread[Gravitino-webserver-148,5,main]=1713348167928} 

### How to reproduce

Run action:
https://github.com/datastrato/gravitino-test/actions/workflows/performance-test.yml

**Comment by yuqi1129** [comment]
Some thread was blocked by socket,  I suspect there is a problem with the MySQL instance. 
<img width="1576" alt="image" src="https://github.com/datastrato/gravitino/assets/15794564/d20d19e0-e2ca-48b6-8727-ecdbccf8b528">

**Comment by yuqi1129** [comment]
The data is too large for list operation and thus cause OOM

```
2024-04-22 13:28:00.517 ERROR [Gravitino-webserver-34] [com.datastrato.gravitino.server.web.rest.ExceptionHandlers$BaseExceptionHandler.handle(ExceptionHandlers.java:496)] - Failed to operate object operation [LIST] under [mydb_tree_22], reason [Java heap space]
com.datastrato.gravitino.exceptions.GravitinoRuntimeException: Java heap space
        at com.datastrato.gravitino.catalog.mysql.converter.MysqlExceptionConverter.toGravitinoException(MysqlExceptionConverter.java:33) ~[?:?]
        at com.datastrato.gravitino.catalog.mysql.operation.MysqlTableOperations.listTables(MysqlTableOperations.java:70) ~[?:?]
        at com.datastrato.gravitino.catalog.jdbc.JdbcCatalogOperations.listTables(JdbcCatalogOperations.java:261) ~[?:?]
        at com.datastrato.gravitino.catalog.TableOperationDispatcher.lambda$listTables$0(TableOperationDispatcher.java:67) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
        at com.datastrato.gravitino.catalog.CatalogManager$CatalogWrapper.lambda$doWithTableOps$1(CatalogManager.java:108) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
        at com.datastrato.gravitino.utils.IsolatedClassLoader.withClassLoader(IsolatedClassLoader.java:72) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
        at com.datastrato.gravitino.catalog.CatalogManager$CatalogWrapper.doWithTableOps(CatalogManager.java:103) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
        at com.datastrato.gravitino.catalog.TableOperationDispatcher.lambda$listTables$1(TableOperationDispatcher.java:67) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
        at com.datastrato.gravitino.catalog.OperationDispatcher.doWithCatalog(OperationDispatcher.java:68) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
        at com.datastrato.gravitino.catalog.TableOperationDispatcher.listTables(TableOperationDispatcher.java:65) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
        at com.datastrato.gravitino.catalog.TableNormalizeDispatcher.listTables(TableNormalizeDispatcher.java:37) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
        at com.datastrato.gravitino.listener.TableEventDispatcher.listTables(TableEventDispatcher.java:63) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
        at com.datastrato.gravitino.server.web.rest.TableOperations.lambda$listTables$0(TableOperations.java:75) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
        at com.datastrato.gravitino.lock.TreeLockUtils.doWithTreeLock(TreeLockUtils.java:35) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
        at com.datastrato.gravitino.server.web.rest.TableOperations.lambda$listTables$1(TableOperations.java:72) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
        at java.base/java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.base/javax.security.auth.Subject.doAs(Subject.java:423) ~[?:?]
        at com.datastrato.gravitino.utils.PrincipalUtils.doAs(PrincipalUtils.java:25) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
        at com.datastrato.gravitino.server.web.Utils.doAs(Utils.java:121) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
        at com.datastrato.gravitino.server.web.rest.TableOperations.listTables(TableOperations.java:67) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.41.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.41.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.41.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.41.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.41.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.41.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) ~[jersey-server-2.41.jar:?]
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[jersey-container-servlet-core-2.41.jar:?]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-2.41.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358) ~[jersey-container-servlet-core-2.41.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311) ~[jersey-container-servlet-core-2.41.jar:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-2.41.jar:?]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at com.datastrato.gravitino.server.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:59) ~[gravitino-server-common-0.5.0-SNAPSHOT.jar:?]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at com.datastrato.gravitino.server.web.VersioningFilter.doFilter(VersioningFilter.java:97) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[jetty-security-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
        at java.base/java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.sql.SQLException: Java heap space
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[?:?]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[?:?]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[?:?]
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009) ~[?:?]
        at com.mysql.cj.jdbc.DatabaseMetaDataUsingInfoSchema.executeMetadataQuery(DatabaseMetaDataUsingInfoSchema.java:70) ~[?:?]
        at com.mysql.cj.jdbc.DatabaseMetaDataUsingInfoSchema.getTables(DatabaseMetaDataUsingInfoSchema.java:871) ~[?:?]
        at org.apache.commons.dbcp2.DelegatingDatabaseMetaData.getTables(DelegatingDatabaseMetaData.java:901) ~[commons-dbcp2-2.11.0.jar:2.11.0]
        at org.apache.commons.dbcp2.DelegatingDatabaseMetaData.getTables(DelegatingDatabaseMetaData.java:901) ~[commons-dbcp2-2.11.0.jar:2.11.0]
        at com.datastrato.gravitino.catalog.jdbc.operation.JdbcTableOperations.getTables(JdbcTableOperations.java:253) ~[?:?]
        at com.datastrato.gravitino.catalog.mysql.operation.MysqlTableOperations.listTables(MysqlTableOperations.java:61) ~[?:?]
        ... 83 more
Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by yuqi1129** [comment]
Not a problem
