### ISSUE TITLE
[Bug report] Failed to run spark sql with spark-connector-runtime.jar

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#3059]
### Version

main branch

### Describe what's wrong

Failed to run spark sql with spark-connector-runtime.jar

### Error message and/or stacktrace

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/datastrato/gravitino/shaded/org/apache/spark/api/plugin/SparkPlugin
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:225)
	at org.apache.spark.util.Utils$.$anonfun$loadExtensions$1(Utils.scala:2946)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at org.apache.spark.util.Utils$.loadExtensions(Utils.scala:2944)
	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:207)
	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:193)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:565)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2740)
	at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$2(SparkSession.scala:1026)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:1020)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLEnv$.init(SparkSQLEnv.scala:64)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.<init>(SparkSQLCLIDriver.scala:358)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:174)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

### How to reproduce

Run spark sql with spark-connector-runtime.jar

**Comment by jerryshao** [comment]
Why do you shade gravitino related code, all you need to shade is the third-party library.

**Comment by FANNG1** [comment]
> SparkPlugin

not shade gravitino related code, it's spark code

**Comment by jerryshao** [comment]
Why do you package Spark dependency into the uber jar, I think all the spark dependency provided by Spark, no need to package into the uber jar.

**Comment by FANNG1** [comment]
> Why do you package Spark dependency into the uber jar, I think all the spark dependency provided by Spark, no need to package into the uber jar.

Spark jar is not packaged to spark-connector, the main problem is shading `org.apache`, spark package reference will be shaded to `com/datastrato/gravitino/shaded/org/apache/spark`, but spark package is not build in spark-connector, leading ClassNotFound exception.

**Comment by FANNG1** [comment]
> > Why do you package Spark dependency into the uber jar, I think all the spark dependency provided by Spark, no need to package into the uber jar.
> 
> Spark jar is not packaged to spark-connector, the main problem is shading `org.apache`, spark package reference will be shaded to `com/datastrato/gravitino/shaded/org/apache/spark`, but shaded spark package is not build in spark-connector, leading ClassNotFound exception.
