### ISSUE TITLE
[Bug report] Unexpected WARN message "Failed to deregister PostgreSQL driver java.sql.SQLException: No suitable driver" when load PG catalog 

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#3161]
### Version

main branch

### Describe what's wrong

1.  Unexpected WARN message "Failed to deregister PostgreSQL driver java.sql.SQLException: No suitable driver" when load PG catalog 
2. WARN message in gravitino-server.out : "JDBC URL invalid port number: dummy_port"
3. WARN message in gravitino-server.out : "JAXBContext implementation could not be found. WADL feature is disabled."

### Error message and/or stacktrace

cat gravitino-server.out

```
4月 23, 2024 5:55:00 下午 org.glassfish.jersey.server.wadl.WadlFeature configure
警告: JAXBContext implementation could not be found. WADL feature is disabled.
4月 23, 2024 5:55:00 下午 org.glassfish.jersey.server.wadl.WadlFeature configure
警告: JAXBContext implementation could not be found. WADL feature is disabled.
4月 23, 2024 5:55:16 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 6:05:05 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 6:07:15 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 6:11:27 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 6:29:50 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 6:30:29 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
4月 23, 2024 6:33:30 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 6:35:51 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 6:35:56 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 6:38:05 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 6:45:48 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 6:46:03 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 6:47:05 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 7:01:22 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 7:04:00 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 7:32:02 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 7:32:20 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 7:46:07 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 7:52:14 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 7:52:27 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 7:52:40 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 7:55:28 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 8:04:03 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 8:09:26 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 8:09:33 下午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 23, 2024 8:40:53 下午 org.glassfish.jersey.server.wadl.WadlFeature configure
警告: JAXBContext implementation could not be found. WADL feature is disabled.
4月 23, 2024 8:40:54 下午 org.glassfish.jersey.server.wadl.WadlFeature configure
警告: JAXBContext implementation could not be found. WADL feature is disabled.
4月 24, 2024 10:10:16 上午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 24, 2024 10:58:09 上午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 24, 2024 11:06:29 上午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 24, 2024 11:07:22 上午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
4月 24, 2024 11:11:25 上午 org.postgresql.util.PGPropertyUtil convertPgPortToInt
警告: JDBC URL invalid port number: dummy_port
```
Confusing warning message in gravitino server log file:

```
2024-04-24 11:07:22.423 INFO [Gravitino-webserver-44] [org.apache.kafka.common.utils.AppInfoParser$AppInfo.<init>(AppInfoParser.java:119)] - Kafka version: 3.4.0
2024-04-24 11:07:22.423 INFO [Gravitino-webserver-44] [org.apache.kafka.common.utils.AppInfoParser$AppInfo.<init>(AppInfoParser.java:120)] - Kafka commitId: 2e1947d240607d53
2024-04-24 11:07:22.423 INFO [Gravitino-webserver-44] [org.apache.kafka.common.utils.AppInfoParser$AppInfo.<init>(AppInfoParser.java:121)] - Kafka startTimeMs: 1713928042423
2024-04-24 11:07:22.505 INFO [kafka-admin-client-thread | gravitino.v1.uid4522313573165775363-a.catalog_ui] [org.apache.kafka.common.utils.AppInfoParser.unregisterAppInfo(AppInfoParser.java:83)] - App info kafka.admin.client for gravitino.v1.uid4522313573165775363-a.catalog_ui unregistered
2024-04-24 11:07:22.506 INFO [kafka-admin-client-thread | gravitino.v1.uid4522313573165775363-a.catalog_ui] [org.apache.kafka.clients.admin.internals.AdminMetadataManager.updateFailed(AdminMetadataManager.java:235)] - [AdminClient clientId=gravitino.v1.uid4522313573165775363-a.catalog_ui] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
2024-04-24 11:07:22.506 INFO [kafka-admin-client-thread | gravitino.v1.uid4522313573165775363-a.catalog_ui] [org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1359)] - [AdminClient clientId=gravitino.v1.uid4522313573165775363-a.catalog_ui] Timed out 1 remaining operation(s) during close.
2024-04-24 11:07:22.507 INFO [kafka-admin-client-thread | gravitino.v1.uid4522313573165775363-a.catalog_ui] [org.apache.kafka.common.metrics.Metrics.close(Metrics.java:693)] - Metrics scheduler closed
2024-04-24 11:07:22.507 INFO [kafka-admin-client-thread | gravitino.v1.uid4522313573165775363-a.catalog_ui] [org.apache.kafka.common.metrics.Metrics.close(Metrics.java:697)] - Closing reporter org.apache.kafka.common.metrics.JmxReporter
2024-04-24 11:07:22.507 INFO [kafka-admin-client-thread | gravitino.v1.uid4522313573165775363-a.catalog_ui] [org.apache.kafka.common.metrics.Metrics.close(Metrics.java:703)] - Metrics reporters closed
2024-04-24 11:07:22.538 INFO [Gravitino-webserver-44] [com.datastrato.gravitino.catalog.jdbc.MySQLProtocolCompatibleCatalogOperations.close(MySQLProtocolCompatibleCatalogOperations.java:47)] - AbandonedConnectionCleanupThread has been shutdown...
2024-04-24 11:07:22.679 INFO [Gravitino-webserver-44] [org.apache.hadoop.hive.conf.HiveConf.findConfigFile(HiveConf.java:187)] - Found configuration file file:/Users/wangdanhua/Workspace/gravitino/distribution/package/catalogs/hive/conf/hive-site.xml
2024-04-24 11:07:22.729 WARN [Gravitino-webserver-44] [org.apache.hadoop.util.NativeCodeLoader.<clinit>(NativeCodeLoader.java:62)] - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2024-04-24 11:07:22.759 INFO [Gravitino-webserver-44] [com.datastrato.gravitino.catalog.lakehouse.iceberg.utils.IcebergCatalogUtil.loadCatalogBackend(IcebergCatalogUtil.java:74)] - Load catalog backend of hive
2024-04-24 11:07:22.824 INFO [Gravitino-webserver-44] [com.datastrato.gravitino.catalog.jdbc.MySQLProtocolCompatibleCatalogOperations.close(MySQLProtocolCompatibleCatalogOperations.java:47)] - AbandonedConnectionCleanupThread has been shutdown...
2024-04-24 11:07:22.830 WARN [Gravitino-webserver-44] [com.datastrato.gravitino.catalog.postgresql.PostgreSQLCatalogOperations.close(PostgreSQLCatalogOperations.java:44)] - Failed to deregister PostgreSQL driver
java.sql.SQLException: No suitable driver
	at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:299) ~[java.sql:?]
	at com.datastrato.gravitino.catalog.postgresql.PostgreSQLCatalogOperations.close(PostgreSQLCatalogOperations.java:41) ~[gravitino-catalog-jdbc-postgresql-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogManager.$closeResource(CatalogManager.java:609) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogManager.lambda$getHiddenPropertyNames$12(CatalogManager.java:603) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.utils.IsolatedClassLoader.withClassLoader(IsolatedClassLoader.java:72) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.utils.IsolatedClassLoader.withClassLoader(IsolatedClassLoader.java:91) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogManager.getHiddenPropertyNames(CatalogManager.java:595) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.catalog.CatalogManager.lambda$listCatalogsInfo$3(CatalogManager.java:266) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:297) ~[guava-32.1.3-jre.jar:?]
	at com.datastrato.gravitino.catalog.CatalogManager.listCatalogsInfo(CatalogManager.java:266) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.listener.CatalogEventDispatcher.listCatalogsInfo(CatalogEventDispatcher.java:69) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.server.web.rest.CatalogOperations.lambda$listCatalogs$0(CatalogOperations.java:73) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.lock.TreeLockUtils.doWithTreeLock(TreeLockUtils.java:35) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.server.web.rest.CatalogOperations.lambda$listCatalogs$1(CatalogOperations.java:68) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
	at java.base/javax.security.auth.Subject.doAs(Subject.java:439) ~[?:?]
	at com.datastrato.gravitino.utils.PrincipalUtils.doAs(PrincipalUtils.java:25) ~[gravitino-core-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.server.web.Utils.doAs(Utils.java:121) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
	at com.datastrato.gravitino.server.web.rest.CatalogOperations.listCatalogs(CatalogOperations.java:63) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.41.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) ~[jersey-server-2.41.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-2.41.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at com.datastrato.gravitino.server.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:59) ~[gravitino-server-common-0.5.0-SNAPSHOT.jar:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at com.datastrato.gravitino.server.web.VersioningFilter.doFilter(VersioningFilter.java:97) ~[gravitino-server-0.5.0-SNAPSHOT.jar:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[jetty-security-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[jetty-servlet-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [jetty-util-9.4.51.v20230217.jar:9.4.51.v20230217]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]

```

### How to reproduce

Load pg catalog in gravitino

<img width="386" alt="image" src="https://github.com/datastrato/gravitino/assets/154112360/b4c94ef5-9354-4cf7-a775-90fa1400c4bf">

**Comment by jerryshao** [comment]
@yuqi1129 can you please take a look.
