### ISSUE TITLE
[Bug report] `./gradlew test -PskipITs` failed in python-client test

### ISSUE THREAD

**Issue by jerryshao** [datastrato/gravitino#3319]
### Version

main branch

### Describe what's wrong

When running this command `./gradlew test -PskipITs` directly. the Gradle python test task will be failed because of lacking compileDistribution step. we should fix it to make all the commands work.

### Error message and/or stacktrace

```shell
➜  gravitino git:(python-formatter) ✗ ./gradlew test -PskipITs

> Configure project :
checkContainerRunning command execution failed: Process 'command 'bash'' finished with non-zero exit value 1
Current docker context is: orbstack

------------------ Check Docker environment ---------------------
Docker server status ............................................ [running]
mac-docker-connector status ..................................... [stop]
OrbStack status ................................................. [yes]
Using Gravitino IT Docker container to run all integration tests. [embedded test]
-----------------------------------------------------------------

> Configure project :web
Kotlin DSL property assignment is an incubating feature.

> Task :clients:client-python:pipInstall
Executing command: 'sh -c . /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/bin/activate >/dev/null 2>&1 && conda activate python-3.8 >/dev/null 2>&1 && pip install -e .[dev]'
Obtaining file:///Users/jerryshao/Projects/gravitino/clients/client-python
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: requests in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from gravitino==0.5.0) (2.31.0)
Requirement already satisfied: dataclasses-json in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from gravitino==0.5.0) (0.6.4)
Requirement already satisfied: pylint in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from gravitino==0.5.0) (3.1.0)
Requirement already satisfied: black in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from gravitino==0.5.0) (24.4.2)
Requirement already satisfied: click>=8.0.0 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from black->gravitino==0.5.0) (8.1.7)
Requirement already satisfied: mypy-extensions>=0.4.3 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from black->gravitino==0.5.0) (1.0.0)
Requirement already satisfied: packaging>=22.0 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from black->gravitino==0.5.0) (24.0)
Requirement already satisfied: pathspec>=0.9.0 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from black->gravitino==0.5.0) (0.12.1)
Requirement already satisfied: platformdirs>=2 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from black->gravitino==0.5.0) (4.2.1)
Requirement already satisfied: tomli>=1.1.0 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from black->gravitino==0.5.0) (2.0.1)
Requirement already satisfied: typing-extensions>=4.0.1 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from black->gravitino==0.5.0) (4.11.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from dataclasses-json->gravitino==0.5.0) (3.21.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from dataclasses-json->gravitino==0.5.0) (0.9.0)
Requirement already satisfied: astroid<=3.2.0-dev0,>=3.1.0 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from pylint->gravitino==0.5.0) (3.1.0)
Requirement already satisfied: isort!=5.13.0,<6,>=4.2.5 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from pylint->gravitino==0.5.0) (5.13.2)
Requirement already satisfied: mccabe<0.8,>=0.6 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from pylint->gravitino==0.5.0) (0.7.0)
Requirement already satisfied: tomlkit>=0.10.1 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from pylint->gravitino==0.5.0) (0.12.5)
Requirement already satisfied: dill>=0.2 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from pylint->gravitino==0.5.0) (0.3.8)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from requests->gravitino==0.5.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from requests->gravitino==0.5.0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from requests->gravitino==0.5.0) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/envs/python-3.8/lib/python3.8/site-packages (from requests->gravitino==0.5.0) (2024.2.2)
Installing collected packages: gravitino
  Attempting uninstall: gravitino
    Found existing installation: gravitino 0.5.0
    Uninstalling gravitino-0.5.0:
      Successfully uninstalled gravitino-0.5.0
  Running setup.py develop for gravitino
Successfully installed gravitino-0.5.0

> Task :clients:client-python:black
Executing command: 'sh -c . /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/bin/activate >/dev/null 2>&1 && conda activate python-3.8 >/dev/null 2>&1 && black ./gravitino ./tests'
All done! ✨ 🍰 ✨
78 files left unchanged.

> Task :clients:client-python:pylint
Executing command: 'sh -c . /Users/jerryshao/Projects/gravitino/.gradle/python/MacOSX/Miniforge3/bin/activate >/dev/null 2>&1 && conda activate python-3.8 >/dev/null 2>&1 && pylint ./gravitino ./tests'

> Task :catalogs:catalog-jdbc-common:compileTestJava
注: /Users/jerryshao/Projects/gravitino/catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/utils/TestJdbcConfig.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

> Task :common:compileTestJava
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

> Task :clients:client-java:compileTestJava
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

> Task :spark-connector:spark-connector:compileTestJava
注: /Users/jerryshao/Projects/gravitino/spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/catalog/TestTransformTableChange.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

> Task :clients:filesystem-hadoop3:compileTestJava
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

> Task :server:compileTestJava
注: /Users/jerryshao/Projects/gravitino/server/src/test/java/com/datastrato/gravitino/server/web/TestVersioningFilter.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

> Task :clients:client-python:pylint

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)


> Task :catalogs:catalog-jdbc-postgresql:compileTestJava
注: /Users/jerryshao/Projects/gravitino/catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

> Task :catalogs:catalog-hive:compileTestJava
注: /Users/jerryshao/Projects/gravitino/catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/integration/test/ProxyCatalogHiveIT.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

> Task :core:compileTestJava
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

> Task :clients:client-python:test FAILED

> Task :integration-test:compileTestJava
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

> Task :catalogs:catalog-lakehouse-iceberg:compileTestJava
注: /Users/jerryshao/Projects/gravitino/catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/IcebergRESTServiceIT.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

Build gravitino FAILURE reason:
    Execution failed for task ':clients:client-python:test':
        Caused by: java.io.IOException: Cannot run program "/Users/jerryshao/Projects/gravitino/distribution/package/bin/gravitino.sh": error=2, No such file or directory
            at org.gradle.internal.classpath.Instrumented.start(Instrumented.java:364)
            at Build_gradle.gravitinoServer(build.gradle.kts:25)
            at Build_gradle$$$result$1$test$2$1.execute(build.gradle.kts:58)
            at Build_gradle$$$result$1$test$2$1.execute(build.gradle.kts:57)
            at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:835)
            at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:808)
            at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:248)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
            at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
            at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
            at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
            at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:233)
            at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:216)
            at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:199)
            at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:166)
            at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105)
            at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
            at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59)
            at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
            at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
            at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
            at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
            at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
            at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
            at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:56)
            at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
            at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:67)
            at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:37)
            at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
            at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
            at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
            at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50)
            at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:28)
            at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.executeDelegateBroadcastingChanges(CaptureStateAfterExecutionStep.java:100)
            at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:72)
            at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:50)
            at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:40)
            at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:29)
            at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:179)
            at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:70)
            at org.gradle.internal.Either$Right.fold(Either.java:175)
            at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59)
            at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:68)
            at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:46)
            at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36)
            at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25)
            at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
            at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
            at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:91)
            at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:55)
            at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
            at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:37)
            at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:65)
            at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:36)
            at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
            at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
            at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:77)
            at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:38)
            at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:94)
            at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:49)
            at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:71)
            at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:45)
            at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNonEmptySources(SkipEmptyWorkStep.java:177)
            at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:81)
            at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:53)
            at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
            at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
            at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
            at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
            at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
            at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:75)
            at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:41)
            at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:32)
            at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:293)
            at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
            at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:21)
            at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
            at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
            at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:47)
            at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:34)
            Caused by: java.io.IOException: error=2, No such file or directory
                ... 87 more


FAILURE: Build failed with an exception.
```

### How to reproduce

Just run `./gradlew test -PskipTests` will reproduce this issue.

**Comment by jerryshao** [comment]
@xunliu @noidname01 would you please help to check this issue when you have time.

**Comment by xunliu** [comment]
> @xunliu @noidname01 would you please help to check this issue when you have time.

OK, I will fix this issue.

**Comment by noidname01** [comment]
It seems that `skipPyClientITs` has not been set, so it will run `test` even if `-PskipTests` has been set.
