### ISSUE TITLE
[Subtask] Support Iceberg metadata tables

### ISSUE THREAD

**Issue by caican00** [datastrato/gravitino#3365]
### Describe the subtask

Support Iceberg metadata tables

```
ENTRIES,
FILES,
DATA_FILES,
DELETE_FILES,
HISTORY,
METADATA_LOG_ENTRIES,
SNAPSHOTS,
REFS,
MANIFESTS,
PARTITIONS,
ALL_DATA_FILES,
ALL_DELETE_FILES,
ALL_FILES,
ALL_MANIFESTS,
ALL_ENTRIES,
POSITION_DELETES
```

### Parent issue

https://github.com/datastrato/gravitino/issues/1571

**Comment by caican00** [comment]
There are still some limitation.

```

Table namespace must be non-null and have 3 levels, the input namespace is test.iceberg.default_db.test_iceberg_as_of_query
com.datastrato.gravitino.exceptions.IllegalNamespaceException: Table namespace must be non-null and have 3 levels, the input namespace is test.iceberg.default_db.test_iceberg_as_of_query
	at com.datastrato.gravitino.Namespace.check(Namespace.java:270)
	at com.datastrato.gravitino.Namespace.checkTable(Namespace.java:166)
	at com.datastrato.gravitino.NameIdentifier.checkTable(NameIdentifier.java:174)
	at com.datastrato.gravitino.client.RelationalCatalog.loadTable(RelationalCatalog.java:100)
	at com.datastrato.gravitino.spark.connector.catalog.BaseCatalog.loadGravitinoTable(BaseCatalog.java:580)
	at com.datastrato.gravitino.spark.connector.catalog.BaseCatalog.loadTable(BaseCatalog.java:222)
	at org.apache.spark.sql.connector.catalog.CatalogV2Util$.getTable(CatalogV2Util.scala:355)
	at org.apache.spark.sql.connector.catalog.CatalogV2Util$.loadTable(CatalogV2Util.scala:336)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.$anonfun$resolveRelation$3(Analyzer.scala:1264)
	at scala.Option.orElse(Option.scala:447)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.$anonfun$resolveRelation$1(Analyzer.scala:1263)
	at scala.Option.orElse(Option.scala:447)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.org$apache$spark$sql$catalyst$analysis$Analyzer$ResolveRelations$$resolveRelation(Analyzer.scala:1255)
```
