### ISSUE TITLE
[Bug report] Gravitino intergraiton test failed caused by checkIfServerIsRunning timeout

### ISSUE THREAD

**Issue by zhoukangcn** [datastrato/gravitino#3447]
### Version

main branch

### Describe what's wrong

![image](https://github.com/datastrato/gravitino/assets/6739160/2c205e7f-e483-40fe-beb6-4cf4d8410470)

### Error message and/or stacktrace

```
> Task :integration-test:test
Current project version: 0.6.0-SNAPSHOT

AuditIT > initializationError FAILED
    java.lang.RuntimeException: Gravitino server start failed
        at com.datastrato.gravitino.integration.test.MiniGravitino.start(MiniGravitino.java:162)
        at com.datastrato.gravitino.integration.test.util.AbstractIT.startIntegrationTest(AbstractIT.java:183)
        at com.datastrato.gravitino.integration.test.client.AuditIT.startIntegrationTest(AuditIT.java:30)

        Caused by:
        java.util.concurrent.TimeoutException
            at java.util.concurrent.FutureTask.get(FutureTask.java:205)
            at com.datastrato.gravitino.integration.test.MiniGravitino.start(MiniGravitino.java:160)
            ... 2 more
```

### How to reproduce

It is unstable. It occasionally appear on MacOS

**Comment by zhoukangcn** [comment]
Curl `http://0.0.0.0:2761/api/version` is ok
<img width="1588" alt="image" src="https://github.com/datastrato/gravitino/assets/6739160/88ac58b4-6df5-4cdf-923f-d24294c2b9ee">

but 
```
"Test worker" #1 prio=5 os_prio=31 tid=0x00007feb1e008800 nid=0x2403 runnable [0x0000000308663000]
   java.lang.Thread.State: RUNNABLE
  at java.net.PlainSocketImpl.socketConnect(Native Method)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  - locked <0x00000007b5babce8> (a java.net.SocksSocketImpl)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  at java.net.Socket.connect(Socket.java:607)
  at org.apache.hc.client5.http.socket.PlainConnectionSocketFactory.lambda$connectSocket$0(PlainConnectionSocketFactory.java:85)
  at org.apache.hc.client5.http.socket.PlainConnectionSocketFactory$$Lambda$569/987348198.run(Unknown Source)
  at java.security.AccessController.doPrivileged(Native Method)
  at org.apache.hc.client5.http.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:84)
  at org.apache.hc.client5.http.socket.ConnectionSocketFactory.connectSocket(ConnectionSocketFactory.java:113)
  at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:181)
  at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:447)
  at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:162)
  at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:172)
  at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:142)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement$$Lambda$567/2105428960.proceed(Unknown Source)
  at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement$$Lambda$567/2105428960.proceed(Unknown Source)
  at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement$$Lambda$567/2105428960.proceed(Unknown Source)
  at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement$$Lambda$567/2105428960.proceed(Unknown Source)
  at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
  at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
  at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
  at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:123)
  at com.datastrato.gravitino.client.HTTPClient.execute(HTTPClient.java:367)
  at com.datastrato.gravitino.client.HTTPClient.execute(HTTPClient.java:294)
  at com.datastrato.gravitino.client.HTTPClient.get(HTTPClient.java:463)
  at com.datastrato.gravitino.client.RESTClient.get(RESTClient.java:165)
  at com.datastrato.gravitino.integration.test.MiniGravitino.checkIfServerIsRunning(MiniGravitino.java:253)
  at com.datastrato.gravitino.integration.test.MiniGravitino.start(MiniGravitino.java:152)
  at com.datastrato.gravitino.integration.test.util.AbstractIT.startIntegrationTest(AbstractIT.java:183)
  at com.datastrato.gravitino.integration.test.client.AuditIT.startIntegrationTest(AuditIT.java:30)
```
