### ISSUE TITLE
[Bug report] spark connector failed to start in real spark3.3 envriment

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#3564]
### Version

main branch

### Describe what's wrong

spark connector started start in spark3.3 envriment

### Error message and/or stacktrace

ERROR StatusLogger Unable to create Lookup for ctx
 java.lang.NoSuchMethodError: org.apache.logging.log4j.util.LoaderUtil.newCheckedInstanceOfProperty(Ljava/lang/String;Ljava/lang/Class;Ljava/util/function/Supplier;)Ljava/lang/Object;
	at org.apache.logging.log4j.core.impl.ContextDataInjectorFactory.createInjector(ContextDataInjectorFactory.java:71)
	at org.apache.logging.log4j.core.lookup.ContextMapLookup.<init>(ContextMapLookup.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.logging.log4j.core.util.ReflectionUtil.instantiate(ReflectionUtil.java:188)
	at org.apache.logging.log4j.core.lookup.Interpolator.<init>(Interpolator.java:89)
	at org.apache.logging.log4j.core.lookup.Interpolator.<init>(Interpolator.java:108)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:136)
	at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
	at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:76)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:263)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:222)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:144)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:242)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:46)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:176)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:666)
	at org.apache.logging.log4j.LogManager.getRootLogger(LogManager.java:700)
	at org.apache.spark.internal.Logging.initializeLogging(Logging.scala:130)
	at org.apache.spark.internal.Logging.initializeLogIfNecessary(Logging.scala:115)
	at org.apache.spark.internal.Logging.initializeLogIfNecessary$(Logging.scala:109)
	at org.apache.spark.deploy.SparkSubmit.initializeLogIfNecessary(SparkSubmit.scala:75)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:83)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1072)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1081)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.logging.log4j.util.LoaderUtil.newCheckedInstanceOfProperty(Ljava/lang/String;Ljava/lang/Class;Ljava/util/function/Supplier;)Ljava/lang/Object;
	at org.apache.logging.log4j.core.config.LoggerConfig.<clinit>(LoggerConfig.java:84)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:139)
	at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
	at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:76)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:263)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:222)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:144)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:242)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:46)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:176)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:666)
	at org.apache.logging.log4j.LogManager.getRootLogger(LogManager.java:700)
	at org.apache.spark.internal.Logging.initializeLogging(Logging.scala:130)
	at org.apache.spark.internal.Logging.initializeLogIfNecessary(Logging.scala:115)
	at org.apache.spark.internal.Logging.initializeLogIfNecessary$(Logging.scala:109)
	at org.apache.spark.deploy.SparkSubmit.initializeLogIfNecessary(SparkSubmit.scala:75)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:83)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1072)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1081)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

### How to reproduce

1. download spark 3.3 packageds
2. start Gravitino server 
3. start spark-sql client
./bin/spark-sql -v \
--conf spark.plugins="com.datastrato.gravitino.spark.connector.plugin.GravitinoSparkPlugin" \
--conf spark.sql.gravitino.uri=http://127.0.0.1:8090 \
--conf spark.sql.gravitino.metalake=test \
--conf spark.sql.gravitino.supportsIceberg=true \
--conf spark.hadoop.hive.exec.dynamic.partition.mode=nonstrict \
--conf spark.hadoop.hive.metastore.uris=thrift://127.0.0.1:19083 \
--conf spark.sql.catalog.hive.spark.sql.hive.metastore.jars=path \
--conf spark.sql.catalog.hive.spark.sql.hive.metastore.jars.path="file:///Users/fanng/deploy/hive/lib/*" \
--conf spark.sql.session.timeZone=UTC

**Comment by FANNG1** [comment]
in https://github.com/datastrato/gravitino/pull/3415,  `./gradlew :spark-connector:spark-connector-runtime:build -PsparkVersion=3.3` makes spark connector jar for Spark3.3
