### ISSUE TITLE
[Improvement] IT fail in deploy mode

### ISSUE THREAD

**Issue by mchades** [datastrato/gravitino#3612]
### What would you like to be improved?

IT may run before Gravitino starts, which will cause IT to fail in deployment mode, here are the key logs that prove this:

```java
> Task :integration-test:test

AuditIT > testAuditMetalake() FAILED
    com.datastrato.gravitino.exceptions.RESTException: Error occurred while processing GET request
        at com.datastrato.gravitino.client.HTTPClient.execute(HTTPClient.java:408)
        at com.datastrato.gravitino.client.HTTPClient.execute(HTTPClient.java:294)
        at com.datastrato.gravitino.client.HTTPClient.get(HTTPClient.java:463)
        at com.datastrato.gravitino.client.RESTClient.get(RESTClient.java:165)
        at com.datastrato.gravitino.client.GravitinoClientBase.serverVersion(GravitinoClientBase.java:153)
        at com.datastrato.gravitino.client.GravitinoClientBase.checkVersion(GravitinoClientBase.java:84)
        at com.datastrato.gravitino.client.HTTPClient.performPreConnectHandler(HTTPClient.java:418)
        at com.datastrato.gravitino.client.HTTPClient.execute(HTTPClient.java:340)
        at com.datastrato.gravitino.client.HTTPClient.execute(HTTPClient.java:294)
        at com.datastrato.gravitino.client.HTTPClient.post(HTTPClient.java:488)
        at com.datastrato.gravitino.client.GravitinoAdminClient.createMetalake(GravitinoAdminClient.java:121)
        at com.datastrato.gravitino.integration.test.client.AuditIT.testAuditMetalake(AuditIT.java:39)

        Caused by:
        org.apache.hc.client5.http.HttpHostConnectException: Connect to http://0.0.0.0:8090/ [/0.0.0.0] failed: Connection refused (Connection refused)
            at java.net.PlainSocketImpl.socketConnect(Native Method)
            at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
            at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
            at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
            at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
            at java.net.Socket.connect(Socket.java:607)
            at org.apache.hc.client5.http.socket.PlainConnectionSocketFactory.lambda$connectSocket$0(PlainConnectionSocketFactory.java:85)
            at java.security.AccessController.doPrivileged(Native Method)
            at org.apache.hc.client5.http.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:84)
            at org.apache.hc.client5.http.socket.ConnectionSocketFactory.connectSocket(ConnectionSocketFactory.java:113)
            at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:181)
            at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:447)
            at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:162)
            at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:172)
            at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:142)
            at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
            at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
            at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
            at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
            at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
            at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
            at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
            at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
            at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
            at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
            at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:123)
            at com.datastrato.gravitino.client.HTTPClient.execute(HTTPClient.java:367)
            ... 11 more
```

```java
12:24:19.965 [Test worker] INFO  com.datastrato.gravitino.integration.test.container.ContainerSuite - Docker info: Info(architecture=x86_64, containers=1, containersStopped=0, containersPaused=0, containersRunning=1, cpuCfsPeriod=true, cpuCfsQuota=true, cpuShares=true, cpuSet=true, debug=false, discoveryBackend=null, dockerRootDir=/var/lib/docker, driver=overlay2, driverStatuses=[[Backing Filesystem, extfs], [Supports d_type, true], [Using metacopy, false], [Native Overlay Diff, false], [userxattr, false]], systemStatus=null, plugins={Volume=[local], Network=[bridge, host, ipvlan, macvlan, null, overlay], Authorization=null, Log=[awslogs, fluentd, gcplogs, gelf, journald, json-file, local, logentries, splunk, syslog]}, executionDriver=null, loggingDriver=json-file, experimentalBuild=false, httpProxy=, httpsProxy=, id=828adade-9126-45c5-a536-dc1f57fd1350, ipv4Forwarding=true, bridgeNfIptables=true, bridgeNfIp6tables=true, images=16, indexServerAddress=https://index.docker.io/v1/, initPath=null, initSha1=null, kernelVersion=6.5.0-1021-azure, labels=[], memoryLimit=true, memTotal=16757354496, name=fv-az1149-691, ncpu=4, nEventsListener=0, nfd=31, nGoroutines=46, noProxy=, oomKillDisable=false, osType=linux, oomScoreAdj=null, operatingSystem=Ubuntu 22.04.4 LTS, registryConfig=InfoRegistryConfig(indexConfigs={docker.io=InfoRegistryConfig.IndexConfig(mirrors=[], name=docker.io, official=true, secure=true)}, insecureRegistryCIDRs=[127.0.0.0/8], mirrors=null), sockets=null, swapLimit=true, systemTime=2024-05-28T12:24:19.950158591Z, serverVersion=24.0.9, clusterStore=null, clusterAdvertise=null, swarm=SwarmInfo(nodeID=, nodeAddr=, localNodeState=INACTIVE, controlAvailable=false, error=, remoteManagers=null, nodes=null, managers=null, clusterInfo=null), isolation=, securityOptions=[name=apparmor, name=seccomp,profile=builtin, name=cgroupns])
2024-05-28 12:24:20.123 [Test worker] INFO  com.datastrato.gravitino.integration.test.util.AbstractIT - Running Gravitino Server in deploy mode
2024-05-28 12:24:20.625 [Test worker] INFO  com.datastrato.gravitino.integration.test.util.JdbcDriverDownloader - Start download jdbc-driver from:https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.26/mysql-connector-java-8.0.26.jar
2024-05-28 12:24:21.610 [Test worker] INFO  com.datastrato.gravitino.integration.test.util.JdbcDriverDownloader - Download jdbc-driver:mysql-connector-java-8.0.26.jar success. path:/home/runner/work/gravitino/gravitino/distribution/package/libs/mysql-connector-java-8.0.26.jar
2024-05-28 12:24:21.666 [Test worker] INFO  com.datastrato.gravitino.integration.test.util.CommandExecutor - Sending command "bash -c /home/runner/work/gravitino/gravitino/distribution/package/bin/gravitino.sh start" to localhost
2024-05-28 12:24:28.642 [Test worker] INFO  com.datastrato.gravitino.integration.test.util.PrintFuncNameExtension - ===== Enter test: testAuditMetalake() =====
2024-05-28 12:24:28.825 [Test worker] INFO  com.datastrato.gravitino.integration.test.util.PrintFuncNameExtension - ====== Exit Test: testAuditMetalake() ======
2024-05-28 12:24:28.857 [Test worker] INFO  com.datastrato.gravitino.integration.test.util.CommandExecutor - Sending command "bash -c /home/runner/work/gravitino/gravitino/distribution/package/bin/gravitino.sh stop" to localhost
2024-05-28 12:24:33.294 [Test worker] INFO  com.datastrato.gravitino.integration.test.util.AbstractIT - Tearing down Gravitino Server
2024-05-28 12:24:33.310 [Test worker] INFO  com.datastrato.gravitino.integration.test.util.AbstractIT - Running Gravitino Server in deploy mode
2024-05-28 12:24:33.368 [Test worker] INFO  com.datastrato.gravitino.integration.test.util.CommandExecutor - Sending command "bash -c /home/runner/work/gravitino/gravitino/distribution/package/bin/gravitino.sh start" to localhost
```

### How should we improve?

wait for the Gravitino server to start before running IT in deploy mode

**Comment by rich7420** [comment]
Hello ,  I have an idea . Can we introduce a polling mechanism to check the server status before running the integration tests ? Which command causes this problem? Is `./gradlew test ` ?

**Comment by mchades** [comment]
Hi @rich7420 , thanks for your message.

> Hello , I have an idea . Can we introduce a polling mechanism to check the server status before running the integration tests ?

yeah, you can use `Awaitility` to implement your idea. 

> Which command causes this problem? Is `./gradlew test ` ?

This is not a stable reproducible issue. However, you can trigger an integration test locally in deploy mode using the following command:
`./gradlew  clean && ./gradlew compileDistribution -x test && :integration-test:test --tests "com.datastrato.gravitino.integration.test.client.MetalakeIT"`
 FYI: https://datastrato.ai/docs/0.5.0/how-to-test#run-the-integration-tests-in-embedded-mode

**Comment by rich7420** [comment]
@mchades thank you for your answer me! I will try to reproduce through the command and fix it.

**Comment by rich7420** [comment]
@mchades Hello, Where do you think this dependency` testImplementation 'org.awaitility:awaitility:4.2.1' `should be placed in gradle.build.kts? Is it `setIntegrationTestEnvironment`?

**Comment by mchades** [comment]
> @mchades Hello, Where do you think this dependency`testImplementation 'org.awaitility:awaitility:4.2.1'`should be placed in build.gradle.kts? Is it `setIntegrationTestEnvironment` or `allprojects` ?

in `integration-test/build.gradle.kts`

**Comment by rich7420** [comment]
I create a PR [heere](https://github.com/datastrato/gravitino/pull/3693)

**Comment by rich7420** [comment]
I created new PR [#3735 ] for this issue.
