### ISSUE TITLE
[Bug report] task :web:installDeps failed on ubuntu

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#3622]
### Version

main branch

### Describe what's wrong

task :web:installDeps failed on ubuntu

### Error message and/or stacktrace

```
ERR_PNPM_ENOENT  ENOENT: no such file or directory, copyfile '/Users/fanng/.pnpm-store/v3/files/d1/84bcef7dfc817f9a4e3e9e26900478e40ec7bc5343706d7ade20a097403e30666cc226f7981c5a5402dbeeb5ce2351866c2cb7b46b025638b775971b3b2d71' -> '/Users/fanng/vm/ubuntu/gravitino/web/node_modules/.pnpm/rc-pagination@4.0.4_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/rc-pagination_tmp_8895/es/locale/en_US.d.ts'
Progress: resolved 617, reused 140, downloaded 18, added 18

> Task :web:installDeps FAILED

Build gravitino FAILURE reason:
    Execution failed for task ':web:installDeps':
        org.gradle.process.internal.ExecException: Process 'command '/Users/fanng/vm/ubuntu/gravitino/web/.gradle/pnpm/pnpm-v9.x/bin/pnpm'' finished with non-zero exit value 1
            at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:415)
            at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:38)
```

### How to reproduce

./gradlew :web:installDeps

**Comment by jerryshao** [comment]
Not an issue, mainly due to network problem
