### ISSUE TITLE
[Bug report] CI: Doris container startup failed

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#3791]
### Version

main branch

### Describe what's wrong

Sometimes, CI failed due to  Doris container initialization Error

### Error message and/or stacktrace

CatalogDorisIT > initializationError FAILED
    org.testcontainers.containers.ContainerLaunchException: Container startup failed for image datastrato/gravitino-ci-doris:0.1.3
        at app//org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:361)
        at app//org.testcontainers.containers.GenericContainer.start(GenericContainer.java:334)
        at app//com.datastrato.gravitino.integration.test.container.BaseContainer.start(BaseContainer.java:132)
        at app//com.datastrato.gravitino.integration.test.container.DorisContainer.start(DorisContainer.java:63)
        at app//com.datastrato.gravitino.integration.test.container.ContainerSuite.startDorisContainer(ContainerSuite.java:177)
        at app//com.datastrato.gravitino.catalog.doris.integration.test.CatalogDorisIT.startup(CatalogDorisIT.java:86)

        Caused by:
        org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
            at app//org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
            at app//org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:346)
            ... 5 more

            Caused by:
            org.testcontainers.containers.ContainerLaunchException: Could not create/start container
                at app//org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:565)
                at app//org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:356)
                at app//org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
                ... 6 more

                Caused by:
                org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [32794, 32795] should be listening)
                    at app//org.testcontainers.containers.wait.strategy.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:112)
                    at app//org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
                    at app//org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:978)
                    at app//org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:502)
                    ... 8 more

### How to reproduce

Trigger a integration test workflow

**Comment by zhoukangcn** [comment]
@danhuawang Do you mean Integration test in Github workflow? can you provide the link?

As I know, there is a known issue on #3392

**Comment by danhuawang** [comment]
> @danhuawang Do you mean Integration test in Github workflow? can you provide the link?
> 
> As I know, there is a known issue on #3392

@zhoukangcn  Yes, it failed in Integration test in Github workflow. Here is the link  https://github.com/datastrato/gravitino/actions/runs/9372776274/job/25805009153
https://github.com/datastrato/gravitino/actions/runs/9332535696/job/25688511786

**Comment by zhoukangcn** [comment]
This issue is fixed by #3806, we could close it. @danhuawang
