### ISSUE TITLE
[Bug report]  Cron Integration Test Execution failed for task ':clients:client-python:integrationTest'

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#3832]
### Version

main branch

### Describe what's wrong

<img width="1885" alt="image" src="https://github.com/datastrato/gravitino/assets/154112360/f4749509-78c9-468f-8c89-110e47d09d40">

### Error message and/or stacktrace

```
Task :clients:client-python:integrationTest
Gravitino server status: 
Log dir doesn't exist, create /home/runner/work/gravitino/gravitino/distribution/package/logs
Gravitino Server start success!
Gravitino Server is running[PID:5052]

Executing command: 'sh -c . /home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/bin/activate >/dev/null 2>&1 && conda activate python-3.8 >/dev/null 2>&1 && coverage run --branch -m unittest'
EEE
======================================================================
ERROR: test_fileset_catalog (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_fileset_catalog
Traceback (most recent call last):
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1[251](https://github.com/datastrato/gravitino/actions/runs/9454090272/job/26040890983#step:8:252), in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/gravitino/gravitino/clients/client-python/tests/integration/test_fileset_catalog.py", line 23, in <module>
    class TestFilesetCatalog(IntegrationTestEnv):
  File "/home/runner/work/gravitino/gravitino/clients/client-python/tests/integration/test_fileset_catalog.py", line 60, in TestFilesetCatalog
    gravitino_admin_client: GravitinoAdminClient = GravitinoAdminClient(
  File "/home/runner/work/gravitino/gravitino/clients/client-python/gravitino/client/gravitino_client_base.py", line 41, in __init__
    self.check_version()
  File "/home/runner/work/gravitino/gravitino/clients/client-python/gravitino/client/gravitino_client_base.py", line 74, in check_version
    server_version = self.get_server_version()
  File "/home/runner/work/gravitino/gravitino/clients/client-python/gravitino/client/gravitino_client_base.py", line 110, in get_server_version
    resp = self._rest_client.get("api/version")
  File "/home/runner/work/gravitino/gravitino/clients/client-python/gravitino/utils/http_client.py", line 152, in get
  File "/home/runner/work/gravitino/gravitino/clients/client-python/tests/integration/test_metalake.py", line 22, in <module>
    class TestMetalake(IntegrationTestEnv):
  File "/home/runner/work/gravitino/gravitino/clients/client-python/tests/integration/test_metalake.py", line 36, in TestMetalake
    gravitino_admin_client: GravitinoAdminClient = GravitinoAdminClient(
  File "/home/runner/work/gravitino/gravitino/clients/client-python/gravitino/client/gravitino_client_base.py", line 41, in __init__
    self.check_version()
  File "/home/runner/work/gravitino/gravitino/clients/client-python/gravitino/client/gravitino_client_base.py", line 74, in check_version
    server_version = self.get_server_version()
  File "/home/runner/work/gravitino/gravitino/clients/client-python/gravitino/client/gravitino_client_base.py", line 110, in get_server_version
    resp = self._rest_client.get("api/version")
  File "/home/runner/work/gravitino/gravitino/clients/client-python/gravitino/utils/http_client.py", line 152, in get
    return self._request("get", endpoint, params=params, **kwargs)
  File "/home/runner/work/gravitino/gravitino/clients/client-python/gravitino/utils/http_client.py", line 149, in _request
    return Response(self._make_request(opener, request, timeout=timeout))
  File "/home/runner/work/gravitino/gravitino/clients/client-python/gravitino/utils/http_client.py", line 117, in _make_request
    return opener.open(request, timeout=timeout)
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 1383, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>


======================================================================
ERROR: test_schema (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_schema
Traceback (most recent call last):
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1[256](https://github.com/datastrato/gravitino/actions/runs/9454090272/job/26040890983#step:8:257), in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/home/runner/work/gravitino/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

### How to reproduce

https://github.com/datastrato/gravitino/actions/runs/9454090272/job/26040890983

**Comment by mchades** [comment]
@xunliu Could you please help to take a look? thanks

**Comment by danhuawang** [comment]
```
> Task :clients:client-python:integrationTest
Gravitino server status: 
Gravitino Server start success!
Gravitino Server is running[PID:8336]
Executing command: 'sh -c . /home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/bin/activate >/dev/null 2>&1 && conda activate python-3.8 >/dev/null 2>&1 && coverage run --branch -m unittest'
EEE
======================================================================
ERROR: test_fileset_catalog (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_fileset_catalog
Traceback (most recent call last):
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/socket.py", line [796](https://github.com/danhuawang/gravitino-test/actions/runs/9558632458/job/26347618498#step:8:797), in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/tests/integration/test_fileset_catalog.py", line 23, in <module>
    class TestFilesetCatalog(IntegrationTestEnv):
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/tests/integration/test_fileset_catalog.py", line 60, in TestFilesetCatalog
    gravitino_admin_client: GravitinoAdminClient = GravitinoAdminClient(
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/client/gravitino_client_base.py", line 41, in __init__
    self.check_version()
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/client/gravitino_client_base.py", line 74, in check_version
    server_version = self.get_server_version()
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/client/gravitino_client_base.py", line 110, in get_server_version
    resp = self._rest_client.get("api/version")
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/utils/http_client.py", line 152, in get
    return self._request("get", endpoint, params=params, **kwargs)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/utils/http_client.py", line 149, in _request
    return Response(self._make_request(opener, request, timeout=timeout))
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/utils/http_client.py", line 117, in _make_request
    return opener.open(request, timeout=timeout)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 1383, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
======================================================================
ERROR: test_metalake (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_metalake
Traceback (most recent call last):
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/socket.py", line [808](https://github.com/danhuawang/gravitino-test/actions/runs/9558632458/job/26347618498#step:8:809), in create_connection
    raise err
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/tests/integration/test_metalake.py", line 22, in <module>
    class TestMetalake(IntegrationTestEnv):
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/tests/integration/test_metalake.py", line 36, in TestMetalake
    gravitino_admin_client: GravitinoAdminClient = GravitinoAdminClient(
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/client/gravitino_client_base.py", line 41, in __init__
    self.check_version()
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/client/gravitino_client_base.py", line 74, in check_version
    server_version = self.get_server_version()
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/client/gravitino_client_base.py", line 110, in get_server_version
    resp = self._rest_client.get("api/version")
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/utils/http_client.py", line 152, in get
    return self._request("get", endpoint, params=params, **kwargs)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/utils/http_client.py", line 149, in _request
    return Response(self._make_request(opener, request, timeout=timeout))
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/utils/http_client.py", line 117, in _make_request
    return opener.open(request, timeout=timeout)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 1383, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
======================================================================
ERROR: test_schema (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_schema
Traceback (most recent call last):
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/tests/integration/test_schema.py", line 24, in <module>
    class TestSchema(IntegrationTestEnv):
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/tests/integration/test_schema.py", line 55, in TestSchema
    gravitino_admin_client: GravitinoAdminClient = GravitinoAdminClient(
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/client/gravitino_client_base.py", line 41, in __init__
    self.check_version()
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/client/gravitino_client_base.py", line 74, in check_version
    server_version = self.get_server_version()
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/client/gravitino_client_base.py", line 110, in get_server_version
    resp = self._rest_client.get("api/version")
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/utils/http_client.py", line 152, in get
    return self._request("get", endpoint, params=params, **kwargs)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/utils/http_client.py", line 149, in _request
    return Response(self._make_request(opener, request, timeout=timeout))
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/clients/client-python/gravitino/utils/http_client.py", line 117, in _make_request
    return opener.open(request, timeout=timeout)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 1383, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/envs/python-3.8/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
----------------------------------------------------------------------
Ran 3 tests in 0.001s
FAILED (errors=3)
:clients:client-python:integrationTest failure marker
> Task :clients:client-python:integrationTest FAILED
> Task :clients:client-python:integrationCoverageReport
Executing command: 'sh -c . /home/runner/work/gravitino-test/gravitino-test/gravitino/.gradle/python/Linux/Miniforge3/bin/activate >/dev/null 2>&1 && conda activate python-3.8 >/dev/null 2>&1 && coverage html'
Wrote HTML report to htmlcov/index.html
```

**Comment by xunliu** [comment]
hi, @danhuawang 
This issue looks like the Gravitino Python client can't connect Gravitino Server.
