### ISSUE TITLE
[Bug report] Cron Integration Test: flink-connector:test FAILED

### ISSUE THREAD

**Issue by danhuawang** [datastrato/gravitino#3877]
### Version

main branch

### Describe what's wrong

Task :flink-connector:test

FlinkHiveCatalogIT > initializationError FAILED
    com.datastrato.gravitino.exceptions.RESTException: Error occurred while processing GET request
        at com.datastrato.gravitino.client.HTTPClient.execute(HTTPClient.java:400)
        at com.datastrato.gravitino.client.HTTPClient.execute(HTTPClient.java:286)
        at com.datastrato.gravitino.client.HTTPClient.get(HTTPClient.java:455)
        at com.datastrato.gravitino.client.RESTClient.get(RESTClient.java:165)
        at com.datastrato.gravitino.client.GravitinoClientBase.serverVersion(GravitinoClientBase.java:155)
        at com.datastrato.gravitino.client.GravitinoClientBase.checkVersion(GravitinoClientBase.java:82)
        at com.datastrato.gravitino.client.HTTPClient.performPreConnectHandler(HTTPClient.java:410)
        at com.datastrato.gravitino.client.HTTPClient.execute(HTTPClient.java:332)
        at com.datastrato.gravitino.client.HTTPClient.execute(HTTPClient.java:286)
        at com.datastrato.gravitino.client.HTTPClient.post(HTTPClient.java:480)
        at com.datastrato.gravitino.client.GravitinoAdminClient.createMetalake(GravitinoAdminClient.java:117)
        at com.datastrato.gravitino.flink.connector.integration.test.FlinkEnvIT.initMetalake(FlinkEnvIT.java:78)
        at com.datastrato.gravitino.flink.connector.integration.test.FlinkEnvIT.startUp(FlinkEnvIT.java:47)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeAllMethod(TimeoutExtension.java:68)
        at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

        Caused by:
        org.apache.hc.client5.http.HttpHostConnectException: Connect to http://0.0.0.0:8090 [/0.0.0.0] failed: Connection refused (Connection refused)
            at java.net.PlainSocketImpl.socketConnect(Native Method)
            at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:[350](https://github.com/datastrato/gravitino/actions/runs/9538256924/job/26287256710#step:8:351))
            at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
            at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
            at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
            at java.net.Socket.connect(Socket.java:607)
            at org.apache.hc.client5.http.socket.PlainConnectionSocketFactory.lambda$connectSocket$0(PlainConnectionSocketFactory.java:85)
            at java.security.AccessController.doPrivileged(Native Method)
            at org.apache.hc.client5.http.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:84)
            at org.apache.hc.client5.http.socket.ConnectionSocketFactory.connectSocket(ConnectionSocketFactory.java:113)
            at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:181)
            at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:447)
            at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:162)
            at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:172)
            at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:142)
            at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
            at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
            at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
            at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
            at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
            at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:152)
            at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
            at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
            at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
            at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
            at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:123)
            at com.datastrato.gravitino.client.HTTPClient.execute(HTTPClient.java:[359](https://github.com/datastrato/gravitino/actions/runs/9538256924/job/26287256710#step:8:360))
            ... 86 more

1 test completed, 1 failed
:flink-connector:test failure marker

> Task :flink-connector:test FAILED
Note: /home/runner/work/gravitino/gravitino/catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/IcebergRESTServiceIT.java uses unchecked or unsafe operations.

### Error message and/or stacktrace

https://github.com/datastrato/gravitino/actions/runs/9538256924/job/26287256710
https://github.com/datastrato/gravitino/actions/runs/9530268515/job/26269951407

### How to reproduce

https://github.com/datastrato/gravitino/actions/workflows/cron-integration-test.yml

**Comment by FANNG1** [comment]
close the issue as it not happens.
