### ISSUE TITLE
[Bug report] TrinoConnectorIT may failed in github it

### ISSUE THREAD

**Issue by FANNG1** [datastrato/gravitino#885]
### Describe what's wrong

TrinoConnectorIT may failed in github it

### Error message and/or stacktrace

detailed information: https://github.com/FANNG1/graviton/actions/runs/7041859279/job/19165081070
```
TrinoConnectorIT > initializationError FAILED
    org.testcontainers.containers.ContainerLaunchException: Container startup failed for image datastrato/gravitino-ci-hive:0.1.5
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:361)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:334)
        at com.datastrato.gravitino.integration.test.util.BaseContainer.start(BaseContainer.java:127)
        at com.datastrato.gravitino.integration.test.util.HiveContainer.start(HiveContainer.java:57)
        at com.datastrato.gravitino.integration.test.trino.TrinoConnectorIT.startDockerContainer(TrinoConnectorIT.java:109)

        Caused by:
        org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
            at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
            at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:346)
            ... 4 more

            Caused by:
            org.testcontainers.containers.ContainerLaunchException: Could not create/start container
                at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:565)
                at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:356)
                at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
                ... 5 more

                Caused by:
                org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [32769, 32770, 32771, 32772, 32773, 32774, 32775, 32776, 32777] should be listening)
                    at org.testcontainers.containers.wait.strategy.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:112)
                    at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
                    at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:978)
                    at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:502)
                    ... 7 more
```

**Comment by diqiu50** [comment]
This issue cannot be pinpointed without specific error information. The Docker container logs have now been completed, and the issue will be fixed if it occurs again
