### ISSUE TITLE
[Bug report] Docker network `Pool overlaps with other one on this address space`

### ISSUE THREAD

**Issue by xunliu** [datastrato/gravitino#925]
### Describe what's wrong

When we execute `./gradlew test` command, sometimes the following errors are reported.  #879 
```
Pool overlaps with other one on this address space
```

We through executing `docker network prune` command fixed this issue in the CentOS.

### Error message and/or stacktrace

```
2023-11-30 15:06:43 INFO  5:75 - Pulling docker image: datastrato/gravitino-ci-hive:0.1.5. Please be patient; this may take some time but only needs to be done once.
2023-11-30 15:06:44 INFO  5:47 - Starting to pull image
2023-11-30 15:06:44 INFO  5:93 - Pulling image layers:  0 pending,  0 downloaded,  0 extracted, (0 bytes/0 bytes)
2023-11-30 15:06:44 INFO  5:388 - Creating container for image: datastrato/gravitino-ci-hive:0.1.5
2023-11-30 15:06:44 ERROR 5:552 - Could not start container

com.github.dockerjava.api.exception.DockerException: Status 403: {"message":"Pool overlaps with other one on this address space"}

at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:249) ~[testcontainers-1.19.0.jar:1.19.0]
at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:124) ~[testcontainers-1.19.0.jar:1.19.0]
at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateNetworkCmdExec.execute(CreateNetworkCmdExec.java:27) ~[testcontainers-1.19.0.jar:1.19.0]
```

### Additional context

Here's a discussion of this related issue: https://github.com/maxking/docker-mailman/issues/85a

**Comment by jerryshao** [comment]
Fixed.
